return {
    ["anguish"] = {
        "Administrator Charial",
        "Arch Magus Vangl",
        "Damlin Lingering Charge",
        "First Lieutenant Minas",
        "Grenlok the Converter",
        "Keldovan the Harrier",
        "Overlord Mata Muram",
        "Tanthi the Tormentor",
        "Tantho the Tormentor",
        "Tanthu the Tormentor",
        "Ture",
        "Vilria the Keeper",
        "Warden Hanvar",
    },

    ["chamberse"] = {
        "Construct of Fire",
        "Construct of Power",
        "Construct of Ice",
        "Construct of Pain",
        "Construct of Brutality",
        "Master of Ingenuity",
    },

    ["chambersd"] = {
        "Master of Specialization",
        "Master of Versatility",
        "Master of Versatility",
    },

    ["chambersc"] = {
        "Dragorn Spellscribe",
        "Dragorn Incinerator",
        "Dragorn Flamecaster",
        "Dragorn Acolyte",
        "Dragorn Adept",
        "Dragorn Annihilator",
        "Master of Subversion",
    },

    ["tacvi"] = {
        "Pixtt Xxeric Kex",
        "Pixtt Kretv Krakxt",
        "Zun`Muram Shaldn Boc",
        "Zun`Muram Mordl Delt",
        "Zun`Muram Yihst Vor",
        "Pixtt Riel Tavas",
        "Tunat`Muram Cuu Vauax",
        "Zun`Muram Kvxe Pirik",
        "Tunat`Muram Cuu Vauax",
        "Tunat`Muram Cuu Vauax",
        "Tunat`Muram Cuu Vauax",
        "Pixtt Kretv Kakxt",
        "Pixtt Kretv Kakxt",
    },

    ["txevu"] = {
        "Ukun Bloodfeaster",
        "Aneuk Nyrt Ymosa",
        "Aneuk Rilst Uskst",
        "Mastruq Champion",
        "Ixt Hsek Syat",
        "High Priest Nkosi Bakari",
        "Ancient Cragbeast Matriarch",
        "Ikaav Nysf Lleiv",
        "Inquisitor Lliev Kinth",
        "Inquisitor Chiak Tansk",
        "Zun`Muram Tkarish Zyk",
    },

    ["inktuta"] = {
        "Kelekdrix, Herald of Trushar",
        "Cursecaller Xavonique",
        "Cursecaller Qibaiz",
        "Noqufiel",
        "True Image of Noqufiel",
    },

    ["wallofslaughter"] = {
        "Feran Bloodkeeper",
        "Noc Shadowkeeper",
        "Discordling Warfiend",
        "Girplan Guardian",
        "Pyrique`s Shadow",
        "The Murkglider Hivequeen",
        "Cipheron",
        "Durunal the Cursebearer",
        "Lightning Lord",
        "Hulcror",
    },

    ["provinggrounds"] = {
        "Possessed Brute",
        "Lightningcaller Vhalek",
        "Diad the Devourer",
    },

    ["dranikhollowsc"] = {
        "Silentpaw",
        "a Shrewd Dragorn",
        "Inky Murkglider",
        "Muridae the Plagued",
    },

    ["dranik"] = {
        "Ungi the Swift",
        "Vornad Deathtusk",
        "Kyv Sharpshooter",
        "Mistress Ujani",
        "Tiorpat Tornwing",
        "Ungorn the Furious",
        "Ukun Fleshhunter",
        "Murkglider Breeder",
        "Kyv Sharpshooter Nass",
        "Lirah the Bridgekeeper",
        "Souldrainer",
        "Lhranc",
        "Gronogg the Awful",
        "Arlagai the Defiler",
        "Rargari the Destroyer",
    },

    ["potimeb"] = {
        "Avatar of the Elements",
        "Supernatural Guardian",
        "Terris Thule",
        "Saryrn",
        "Vallon Zek",
        "Tallon Zek",
        "Bertoxxulous",
        "Cazic Thule",
        "Innoruuk",
        "Rallos Zek",
        "Quarm",
    },

}
