return {
    ["blackburrow"] = {
        "Lord Elgnub",
        "Socho Darkpaw",
        "The Fabled Master Brewer",
        "The Mannan of the Sabertooth",
        "The Master Brewer",
        "Tranixx Darkpaw",
    },

    ["everfrost"] = {
        "Tundra Jack",
        "Iceberg",
        "The Ultrafabled Thundra Jack",
        "The Ultrafabled Iceberg",
        "Icebane",
        "Tuskbreaker",
    },

    ["gukbottom"] = {
        "a frenzied ghoul",
        "The Fabled Evil Eye",
        "The Fabled Frenzied Ghoul",
        "The Fabled Froglok Noble",
        "The Fabled Ghoul Assassin",
        "The Fabled Ghoul Cavalier",
        "The Fabled Ghoul Executioner",
        "The Fabled Ghoul Lord",
        "The Fabled Minotaur Patriarch",
        "the ghoul lord",
        "The Ghoul Lord",
        "Timeless Evil Eye",
        "Timeless Frenzied Ghoul",
        "Timeless Ghoul Cavalier",
        "Timeless Ghoul Lord",
        "Timeless Minotaur Patriarch",
    },

    ["kedge"] = {
        "Phinigel Autropos",
        "The Fabled Estrella of Gloomwater",
        "The Fabled Undertow",
        "Estrella of Gloomwater",
    },

    ["mistmoore"] = {
        "Garton Viswin",
        "Maid Issis",
        "Sir Bronthas",
        "The Fabled Cloaked Dhampyre",
        "The Fabled Lasna Cheroone",
        "The Fabled Maid Issis",
        "The Ultrafabled Lasna Cheroone",
    },

    ["soldungb"] = {
        "Efreeti Lord Djarn",
        "Lord Nagafen",
        "King Tranix",
        "The Fabled Death Beetle",
        "The Fabled Efreeti Lord Djarn",
        "The Fabled King Tranix",
        "The Fabled Kobold Noble",
        "The Fabled Magus Rokyl",
        "The Fabled Warlord Skarlon",
        "Warlord Skarlon",
        "The Fabled Efreeti Lord Djarn II",
        "The Fabled Lord Nagafen",
        "The Fabled King Tranix II",
        "The Fabled Magus Rokyl II",
        "The Fabled Neiroth",
        "The Fabled Solusek Queen",
        "The Fabled Warlord Skarlon II",
        "Zordak Ragefire the Ashen Conqueror",
    },

    ["qeynos2"] = {
        "The Fabled Fippy Darkpaw",
        "The Ultrafabled Fippy Darkpaw",
        "The Ultrafabled Nixx Darkpaw",
    },

    ["northkarana"] = {
        "GrimBeak",
        "GrimClaw",
        "GrimEye",
        "GrimFeather",
    },

    ["oasis"] = {
        "The Fabled Phezel",
        "The Fabled Lockjaw",
        "Cazel",
        "The Ultrafabled Arthikus",
        "The Ultrafabled Phezel",
        "Timeless Lockjaw",
        "Timeless Cazel",
    },

    ["oot"] = {
        "Allizewsaur",
        "The Fabled Allizewsaur",
    },

    ["permafrost"] = {
        "Lady Vox",
        "The Fabled Ice Goblin Alchemist",
        "Queen Ahex`Ka",
        "The Fabled Elite Honor Guard",
        "Emperor Thon`Nex",
        "Ice Goblin Philosopher",
        "Ice Goblin Slave Master",
        "Lady Vox' Sister",
        "The Fabled Queen Ahex`Ka",
        "The Fabled Chilling Terror",
        "The Fabled Ice Witch",
        "The Fabled Lady Vox",
    },

    ["rathemtn"] = {
        "Broog Bloodbeard",
        "Chieftain Eyclopse",
    },

    ["fearplane"] = {
        "Cazic Thule",
    },

    ["hateplane"] = {
        "Dark Apostle",
        "Innoruuk",
        "The Deathrot Knight",
        "The Fabled Master of Spite",
    },

    ["hateplaneb"] = {
        "The Ultrafabled Master of Spite",
        "Timeless Arcanist V`Gimis",
        "Timeless Assassin Z`Jrix",
        "Timeless Avatar of Abhorrence",
        "Timeless Dread Lord M`Noxin",
        "Timeless Deathrot Knight",
        "Timeless Hand of the Maestro",
        "Timeless Innoruuk",
        "Timeless Mistress of Malevolence",
        "Timeless Maestro of Rancor",
        "Timeless Evangelist",
    },

    ["burningwood"] = {
        "Ixiblat Fer",
    },

    ["citymist"] = {
        "The Fabled Neh`Ashiir",
    },

    ["chardok"] = {
        "Overking Bathezid",
        "Queen Velazul Di`zok",
    },

    ["chardokb"] = {
        "Korucust",
    },

    ["dreadlands"] = {
        "Gorenaire",
        "The Fabled Gorenaire",
    },

    ["emeraldjungle"] = {
        "Severilous",
        "The Fabled Severilous",
        "The Ultrafabled Severilous",
    },

    ["charasis"] = {
        "Drusella Sathir",
        "The Fabled Crypt Excavator",
        "The Fabled Crypt Spectre",
        "The Fabled Drusella Sathir",
        "The Fabled Skeletal Procurator",
    },

    ["karnor"] = {
        "The Fabled Construct of Sathir",
        "The Fabled Drolvarg Captain",
        "The Fabled Drolvarg Warlord",
        "The Fabled Skeletal Berserker",
        "The Fabled Skeletal Captain",
        "The Fabled Skeletal Warlord",
        "The Fabled Undead Jailer",
        "The Ultrafabled Skeletal Fury",
        "The Ultrafabled Drolvarg Captain",
        "Venril Sathir",
        "The Fabled Decaying Prisoner",
        "The Fabled Knight of Sathir",
        "The Fabled Senior Drolvarg Captain",
        "The Fabled Skeletal Fury",
        "The Fabled Venril Sathir",
        "The Mightforged Sentinel of Karnor",
    },

    ["sebilis"] = {
        "Emperor Chottal",
        "Sebilis Protector",
        "The Fabled Arch Duke Iatol",
        "The Fabled Baron Yosig",
        "The Fabled Brogg",
        "The Fabled Emperor Chottal",
        "The Fabled Froglok Bartender",
        "The Fabled Froglok Chef",
        "The Fabled Gruplinort",
        "The Fabled Harbinger Freglor",
        "The Fabled Hierophant Prime Grekal",
        "The Fabled Myconid Spore King",
        "The Fabled Myconid Warrior",
        "The Fabled Sebilite Guardian",
        "The Fabled Skeletal Crusader",
        "The Fabled Tolapumj",
        "Tolapumj",
        "Trakanon",
        "Ancient Myconid Spore Empress",
        "Spectral Assassin of Chottal",
        "The Fabled Sebilite Protector",
        "The Fabled Trakanon",
        "Froglok Maak Knight",
        "Sebilite Juggernaut",
        "The Ultrafabled Arch Duke Latol",
        "The Ultrafabled Baron Yosig",
        "The Ultrafabled Emperor Chottal",
        "The Ultrafabled Ninja Froglok",
        "The Ultrafabled Sebilis Warrior",
        "The Skeletal Crusader",
        "The Ultrafabled Spectral Assassin",
        "Timeless Brogg",
        "Timeless Froglok Bartender",
        "Timeless Froglok Chef",
        "Timeless Gangrenous Scarab",
        "Timeless Gruplinort",
        "Timeless Harbinger Freglor",
        "Timeless Hierophant Prime Grekal",
        "Timeless Myconid Spellguard",
        "Timeless Myconid Spore Empress",
        "Timeless Revenant Duchess",
        "Timeless Sebilite Guardian",
        "Timeless Sebilite Protector",
        "Timeless Tolapumj",
        "Timeless Trakanon",
    },

    ["skyfire"] = {
        "Talendor",
        "The Ultrafabled Talendor",
    },

    ["veeshan"] = {
        "Ancient Faydrake of Veeshan",
        "Ancient Gatekeeper of Veeshan",
        "Druushk",
        "Hoshkar",
        "Guardian of Veeshan",
        "Nexona",
        "Phara Dar",
        "Silverwing",
        "Xygoz",
        "Ragnoor the Defender",
        "Blazetalon the Dragonblooded",
        "Blazetalon the Ancient",
        "Copperwing",
        "Granithide",
        "Lavatail",
        "Lady Tay",
        "Nerro",
        "Pyroskarn the Embercoil",
        "The Azure Warden",
        "Thalmyra of the Gleaming Coil", },

    ["necropolis"] = {
        "Zlandicar",
    },

    ["eastwastes"] = {
        "Egg Hunter",
        "The Fabled Snow Bunny",
    },

    ["greatdivide"] = {
        "The Fabled Icetooth",
        "Narandi the Wretched",
    },

    ["kael"] = {
        "Dlammaz Stormslayer",
        "Deraktor the Vindicator",
        "The Statue of Rallos Zek",
        "The Idol of Rallos Zek",
        "The Avatar of War",
        "King Tormax",
        "Chief Adjutant Isabella",
        "Queen Tarmax",
        "Forsaken Efreeti of Kael",
        "The Fabled Derakor the Vindicator",
        "The Fabled Fjoka Frozenshard",
        "The Fabled Kallis Stormcaller",
        "The Fabled Klraggek the Slayer",
        "The Fabled King Tormax",
        "The Fabled Statue of Rallos Zek",
        "The Fabled Idol of Rallos Zek",
        "The Fabled Avatar of War",
        "The Fabled Queen Tarmax",
        "Hsagra, The Green Dragoness",
        "Timeless Avatar of War",
        "Timeless Deraktor the Vindicator",
        "Timeless King Tormax",
        "Timeless Idol of Rallos Zek",
        "Timeless Statue of Rallos Zek",
        "Ultrafabled Queen Tarmax",
    },

    ["growthplane"] = {
        "Tunare",
        "The Ultrafabled Rumbleroot",
        "Timeless Idol of War",
    },

    ["sleeper"] = {
        "The Fabled Vyskudra the Ancient",
        "The Fabled Progenitor",
        "The Final Arbiter",
        "The Progenitor",
        "Tjudawos the Ancient",
        "Vyskudra the Ancient",
    },

    ["sirens"] = {
        "Fellspine",
        "The Fabled Fellspine",
        "The Fabled High Priestess Sercema",
        "The Fabled Mistress Latazura",
        "Felicita of Darkwater",
        "High Priestess Sercema",
        "Mistress Latazura",
    },

    ["skyshrine"] = {
        "Lord Yelinak",
    },

    ["templeveeshan"] = {
        "Aaryonar",
        "Dagarn the Destroyer",
        "Eashen of the Sky",
        "Ikatiar the Venom",
        "Lord Feshlak",
        "Lord Kreizenn",
        "Lord Koi`Doken",
        "Lady Mirenilla",
        "Lady Nevederia",
        "Lord Vyemm",
        "The Fabled Eashen of the Sky",
        "The Fabled Gozzrem",
        "Vulak'Aerr",
    },

    ["thurgadinb"] = {
        "Dain Frostreaver IV",
    },

    ["toskirakk"] = {
        "Brusk of Oggok",
        "Captain Tregenek",
        "Frundil",
        "Ganekk Dopp",
        "General Arblok",
        "General Bardak",
        "General Grusix",
        "General Lobroan",
        "Griddunk",
        "Ragnarok Steelwrath, Warlord of Zek",
        "Sturk the Insane Froglok Slave",
        "Tonkk the Axestopper",
        "Ulgren Vith",
        "Vessa the Oracle",
        "Vruten the Intendant",
        "Zharog Bonecleaver",
        "Gorvash Bloodmarauder, Shadow of Zek",
        "Vorruk Skullcleaver, Fury of Zek",
        "Warden Gulgreth",
        "Rallos Zek",
        "Ward Sergeant Krug",
        "Ward Sergeant Razzok",
        "Ward Sergeant Ulgok",
    },

    ["velketor"] = {
        "Bledrek",
        "Kerdelb",
        "Lord Doljonijiarnimorinar",
        "The Fabled Crystal Eyes",
        "The Fabled Crystal Fang",
        "The Fabled Fierce Blizzard Hunter",
        "The Fabled Gregendek Icepaw",
        "The Fabled Lord Doljonijiarnimorinar",
        "The Fabled Tijoely",
        "Triumphant Experiment",
        "Velketor the Sorcerer",
        "The Brood Mother",
        "The Ultrafabled Blizzard Hunteress",
        "The Ultrafabled Brood Mother",
        "The Ultrafabled Lord Doljonijiarnimorinar",
        "The Fabled Bledrek",
        "The Fabled Kerdelb",
        "Velketor the Fabled Sorcerer",
    },

    ["westwastes"] = {
        "Ayillish",
        "Harla Dar",
        "Ionat",
        "Klandicar",
        "Melalafen",
        "Sontalak",
        "The Fabled Ayillish",
        "The Fabled Del Sapara",
        "The Fabled Esorpa of the Ring",
        "The Fabled Harla Dar",
        "The Fabled Ionat",
        "The Fabled Karkona",
        "The Fabled Klandicar",
        "The Fabled Melalafen",
        "The Fabled Sontalak",
        "The Fabled Tantor",
        "The Ultrafabled Ayillish",
        "The Ultrafabled Esorpa of the Ring",
        "The Ultrafabled Gangel",
        "The Ultrafabled Harla Dar",
        "The Ultrafabled Hechaeva",
        "The Ultrafabled Karkona",
        "The Ultrafabled Klandicar",
        "The Ultrafabled Melalafen",
        "The Ultrafabled Sontalak",
        "Timeless Atpaev",
        "Timeless Sontalak",
        "Timeless Strong Horn",
        "Timeless Tantor",
        "Timeless Tranala",
        "Timeless Travala",
        "Timeless Tsiraka",
        "Timeless Zlandicar",
        "Mistress Mistrilla",
        "Lady Yzarma", },

    ["fungusgrove"] = {
        "The Fabled Priest Kak`thak",
        "The Fabled Warlord Tk`kik`tthik",
    },

    ["griegsend"] = {
        "Grieg Veneficius",
    },

    ["sseru"] = {
        "Lord Inquisitor Seru",
    },

    ["ssratemple"] = {
        "Arch Lich Rhag`Zadune",
        "Emperor Ssraeshza",
        "Glyph covered serpent",
        "Vyzh`dra the Cursed",
        "Blood Golem",
    },

    ["umbral"] = {
        "Doomshade",
        "Fleshrot",
        "Rumblecrush",
        "The Fabled Netherbian Swarmcrier",
        "Zelnithak",
        "The Fabled Bloodwretch",
        "The Fabled Doomshade",
        "The Fabled Elysian Elder",
        "The Fabled Fallen Sergeant",
        "The Fabled Fleshrot",
        "The Fabled Netherbian Swarmcaller",
        "The Fabled Rumblecrush",
        "The Fabled Zelnithak", },

    ["vexthal"] = {
        "Aten Ha Ra",
        "Diabo Xi Va",
        "Diabo Xi Va Temariel",
        "Diabo Xi Xin",
        "Diabo Xi Xin Thall",
        "Kaas Thox Xi Ans Dyek",
        "Kaas Thox Xi Aten Ha Ra",
        "Thall Va Kelun",
        "Thall Va Xakra",
        "Thall Xundraux Diabo",
        "Va Xi Aten Ha Ra",
        "Va Dyn Ra",
    },

    ["thegrey"] = {
        "Boulder",
        "Crusader Kezzal",
        "Heirophant Grazan",
        "Revenant Sthzzzizt",
        "Revenant Zsshta",
        "The Fabled Boulder",
        "The Fabled Crusader Kezza",
        "The Fabled Heirophant Grazan",
        "The Fabled Revenant Zsshta",
        "The Fabled Revenant Sthzzzizt",
        "The Ultrafabled Revenant Sthzzzizt",
        "The Ultrafabled Revenant Zsshta",
        "The Pathless Sentinel",
    },

    ["bothunder"] = {
        "Agnarr the Storm Lord",
        "Emmerik Skyfury",
        "The Fabled Bordir Bjomolf",
        "The Fabled Valbrand",
        "The Fabled Wybjorn",
        "The Fabled Agnarr the Storm Lord",
        "The Fabled Brynju Thunderclap",
        "The Fabled Erech Eyford",
        "The Fabled Gaukr Sandstrom",
        "The Fabled Auliffe Chaoswind",
        "The Fabled Eindride Icestorm",
        "The Fabled Hreidar Lynhillig",
        "The Fabled Kuanbyr Hailstorm",
        "The Fabled Laef Windfall",
        "The Fabled Oreen Wavecrasher", },

    ["codecay"] = {
        "Bertoxxulous",
    },

    ["hohonorb"] = {
        "Lord Mithaniel Marr",
        "Ralthazor",
        "Ralthazor, Fabled Champion of Marr",
        "The Fabled Bromal Rythat",
        "The Fabled Lord Mithaniel Marr",
        "The Fabled Rydda`Dar", },

    ["poair"] = {
        "Avatar of Dust",
        "Avatar of Mist",
        "Avatar of Smoke",
        "Xegony",
    },

    ["podisease"] = {
        "Grummus",
        "Aramin the Fabled Spider Guardian",
        "The Fabled Arachnae Parian",
        "The Fabled Diseased Infested Bubonian",
        "The Fabled Grummus",
        "The Fabled Malerian Metamo",
        "The Fabled Rallius Rattican",
        "The Fabled Sengian Fly",
        "The Fabled Skal`s Waking Nightmare", },

    ["poeartha"] = {
        "An Earthen Undercon",
        "A Fabled Perfected Warder of Earth",
        "A Fabled Prismatic Basilisk",
        "Derugoak Bloodwalker",
        "Encrusted Dirt Cloud",
        "Merciless Mudslinger",
        "Mystical Arbitor of Earth",
        "Peregrin Rockskull",
        "A Fabled Mystical Arbitor of Earth",
        "The Fabled Skal's Waking Nightmare",
    },

    ["poearthb"] = {
        "a Rathe Council Man",
        "The Avatar of Earth",
        "War Chieftan Galronar",
        "Warlord Gintolaken",
    },

    ["pofire"] = {
        "Fennin Ro",
        "Hebabbilys the Ragelord",
        "Magmaton",
        "The Fabled General Reparm",
        "The Fabled Vicar of Fire",
        "A Fabled Doomfire Chaoslord",
        "The Fabled Arch Mage Yozanni",
        "The Fabled Azobian the Darklord",
        "The Fabled Babnoxis the Spider Queen",
        "The Fabled Blazzax the Omnifiend",
        "The Fabled Chancellor Kirta",
        "The Fabled Chancellor Traxom",
        "The Fabled Dark Obsidian Lava Spider",
        "The Fabled Doomfire Magus",
        "The Fabled Fennin Ro, Tyrant of Fire",
        "The Fabled Guardian of Doomfire",
        "The Fabled Hebabbilys the Ragelord",
        "Lord Infernon",
        "The Fabled Javonn the Overlord",
        "The Fabled Magma Overlord",
        "The Fabled Magmaton",
        "The Fabled Omni Magus Crato",
        "The Fabled Quavonis Firetail",
        "The Fabled Reaxnous the Chaoslord",
        "The Fabled Warlord Prollaz",
        "The Fabled Wild Fiery Spirit Steed",
        "The Ultrafabled Magmaton",
    },

    ["potactics"] = {
        "Rallos Zek",
        "Tallon Zek",
        "Ancient Statue of War",
        "Guardian of the Halls",
        "Sullon Mclarren",
        "Vallon Zek",
        "Diaku Elite Myrmidon",
        "Hendin Shadow Mistress",
        "Hendin Slavemonger",
        "The Fabled Anival the Blade",
        "The Fabled Deadly Warboar",
        "The Fabled Deathbringer Blackheart",
        "The Fabled Diaku Armorer",
        "The Fabled Guardian of the Halls",
        "The Fabled Tallon Zek",
        "The Fabled Vallon Zek",
        "The Fabled Warlord, Rallos Zek", },

    ["potorment"] = {
        "Saryrn",
        "Maareq the Fabled Prophet",
        "The Fabled Acolyte of Affliction",
        "The Fabled Keeper of Sorrows",
        "The Fabled Salczek the Fleshgrinder",
        "The Fabled Saryrn",
        "The Fabled Sorrowsong",
        "The Fabled Ta`Grusch", },

    ["potimeb"] = {
        "Avatar of the Elements",
        "Supernatural Guardian",
        "Terris Thule",
        "Saryrn",
        "Vallon Zek",
        "Tallon Zek",
        "Bertoxxulous",
        "Cazic Thule",
        "Innoruuk",
        "Rallos Zek",
        "Quarm",
    },

    ["powater"] = {
        "Coirnav",
        "Krziik the Mighty",
        "The Fabled Krziik the Mighty",
    },

    ["solrotower"] = {
        "Jiva",
        "Solusek Ro",
        "The Protector of Dresolik",
        "The Fabled Arlyxir",
        "The Fabled Galremos",
        "The Fabled Jiva",
        "The Fabled Quazlith",
        "The Fabled Naelizar",
        "The Fabled Protector of Dresolik",
        "The Fabled Rizlona",
        "The Fabled Solusek Ro",
        "The Fabled Veleroth",
        "The Fabled Xuzl", },

    ["ferubi"] = {
        "Master`s Apprentice",
        "Packmaster Skoiat Pizak",
        "Smith Rondo",
        "Weapon Master Vtiink Vzaan",
        "Zun`Muram Votal",
    },

    ["ikkinz"] = {
        "Crumbling Monolith",
        "Custodian of Righteousness",
        "Guardian of Righteousness",
        "Spirit of Tunik Tamuik",
        "Visionary of Glory",
        "Sentinel of Glorification",
        "Guardian of Glorification",
        "Guardian of Transcendence",
        "Vrex Xalkak Nixki",
        "Altar Warden",
        "Altar Overseer",
        "Altar Construct",
        "Keeper of the Altar",
    },

    ["inktuta"] = {
        "cursebearer",
        "Kelekdrix, Herald of Trushar",
        "Mirror Image of Noqufiel",
        "True Image of Noqufiel",
    },

    ["kodtaz"] = {
        "Hexxt Chaos Provoker",
        "The Fabled Pixtt Airstrangler",
    },

    ["natimbi"] = {
        "Cragbeast Queen",
    },

    ["qvic"] = {
        "Cynosure Kvanjji",
        "Dvoin M`sha",
        "Mnat M`sha",
        "Ptav M`sha",
        "Iqthinxa Karnkvi",
        "Zun`Hexxt Jkak Miq",
        "Zun`Hexxt Pvin Nki",
        "Zun`Pixtt Invi Mal",
        "Zun`Pixtt Llan Kvish",
        "Krag`Thul the Fabled Bonebreaker",
        "The Fabled Cynosure Kvanjji",
        "The Fabled Dvoin M`sha",
        "The Fabled Iqthinxa Karnkvi",
        "The Fabled Pixtt Invi Mal",
        "The Fabled Pixtt Llan Kvish",
        "The Fabled Zun`Hexxt Jkak Miq",
        "The Fabled Zun`Hexxt Pvin Nki", },

    ["tacvi"] = {
        "Pixtt Kretv Krakxt",
        "Pixtt Riel Tavas",
        "Pixtt Xxeric Kex",
        "Tunat`Muram Cuu Vauax",
        "Zun`Muram Mordl Delt",
        "Zun`Muram Shaldn Boc",
        "Zun`Muram Yihst Vor",
        "The Fabled Llan Kvish",
    },

    ["txevu"] = {
        "Ancient Cragbeast Matriarch",
        "Aneuk Nyrt Ymosa",
        "Aneuk Rilst Uskst",
        "Ikaav Nysf Lleiv",
        "High Priest Nkosi Bakari",
        "Ixt Hsek Syat",
        "Ixt Kial Ivesi",
        "Ixt Quall Nalnn",
        "Mastruq Champion",
        "Ukun Bloodfeaster",
        "Zun`Muram Tkarish Zyk",
    },

    ["uqua"] = {
        "Devastating Construct",
        "Guardian of Destruction",
        "Tqiv Araxt the Enraged",
        "Tqiv Qukret the Furious",
        "Vrex Barxt Qurat",
    },

    ["yxtta"] = {
        "Primal Arachnid",
        "Primal Hynid Warbeast",
        "Primal Insect",
        "Primal Reptile",
        "Primal Ukun Warhound",
        "Pixtt Suir Mindrider",
        "The Fabled Pixtt Suir Mindrider",
    },

    ["anguish"] = {
        "Administrator Charial",
        "Arch Magus Vangl",
        "Damlin Lingering Charge",
        "First Lieutentent Minas",
        "Grenlok the Converter",
        "Keldovan the Harrier",
        "Tanthi the Tormentor",
        "Tantho the Tormentor",
        "Tanthu the Tormentor",
        "Ture",
        "Vipera Ashenheart",
        "Vilria the Keeper",
        "Warden Hanvar",
        "Overlord Mata Muram",
    },

    ["provinggrounds"] = {
        "Master of Versatility",
    },

    ["riftseekers"] = {
        "Chailak",
        "Channeler Pyren",
        "Feratha",
        "King Gelequa",
        "Queen Pyrilonis",
        "Shadowstalker",
    },

    ["wallofslaughter"] = {
        "Cipheron",
        "Hulcror",
        "Shadowhunter",
    },

    ["broodlands"] = {
        "The Broodqueen",
        "Grel Strongboom",
    },

    ["delvea"] = {
        "Spider Broodmother",
        "Stoneclaw",
        "Stonecluster",
        "Stonekrag",
        "Stonemaw",
        "Volkara",
    },

    ["stillmoonb"] = {
        "Kessdona the Enlightened",
        "Razortail",
        "Rikkukin the Defender",
    },

    ["thenest"] = {
        "Ancient Ainslin",
        "Ancient Lavawalker",
        "Ancient Magmeran",
        "Ancient Tremblor",
        "Lavawalker",
        "Magmeran",
        "T'Shara",
        "Vishimtar",
        "Aquila the Sharp",
        "Drake Magus",
    },

    ["stillmoona"] = {
        "Animated Granite Colossus",
        "Animated Granite Guardian",
        "Animated Granite Titan",
        "Celeste the Silent Paw",
        "Hartini the Smart",
        "Icehoof",
        "Nocturna the Stealth Striker",
        "Roqzar the Sapphire Roar",
        "Solstice the Firemane",
        "Thornheart the Mighty Stallion",
        "Valrakor the Fiery Stallion",
        "Villy the Golden",
        "Voltaris the Sharp",
        "Stormmane Thunderhoof",
        "Cinderella",
        "Seraphis",
        "The Mightforged Sentinel of Stillmoon",
        "Valrator the Fiery Stallion",
        "Volaris the Sharp",
    },

    ["thundercrest"] = {
        "Yar'Lir",
    },

    ["delveb"] = {
        "Emoush the Destroyer",
        "Goblin Hall Guardian",
        "Tirranun",
    },

    ["dragoncrypt"] = {
        "Frenzied Heretic",
        "Skaramatra the Fallen",
        "Skaramatra the Risen",
    },

    ["drachnidhive"] = {
        "Drithnak the Exiled",
        "Zummbuk the Vengeful",
    },

    ["westkorlacha"] = {
        "Matriarch Shyra",
        "Overseer Iseek",
        "Prince Drillien",
    },

    ["corathusa"] = {
        "Antraygus, the Sporali King",
    },

    ["arcstone"] = {
        "Champion Ultharas",
        "Coalshade, Oroshars Wake",
        "Embra",
        "Okahn, Hound of Druzzil",
        "Overseer Norgaro",
        "The Colossus of Skylance",
        "Zomm the Seventh Born",
    },

    ["theatera"] = {
        "Ashtar",
        "Melkis",
        "T`Pall",
        "Ayonae Ro",
        "Deathknell Enforcer",
        "Truefaith Bat Keeper",
        "Truefaith Beastmaster",
    },

    ["devastation"] = {
        "Bartol the Cragmaker",
        "Chief Armbreaker",
        "Drishak, the Malevolent",
        "Nydiran the Unrelenting",
        "Ragewind",
        "Savage Fury Lars Hanagar",
        "Savage Fury Marie Gronsmar",
        "Sendaro",
        "Titanothon",
        "Vooersalor the Crafty",
    },

    ["relic"] = {
        "a crashing wave",
        "a demented scrykin",
        "a scrykin firestorm",
        "Ashenback",
        "Lyban",
        "Maru the Twelfth Born",
        "Nightshade",
        "Porthio the Second Born",
        "Shar`Drahn",
        "Sharlash the Ninthborn",
        "The Guardian of the Doorway",
        "Thanus the Eleventh Born",
        "Tsikut",
    },

    ["ragea"] = {
        "Ghost, Guardian of Razorthorn",
        "Snowtail, Guardian of Razorthorn",
        "Sullon Zek, Mistress of Rage",
    },

    ["takishruins"] = {
        "Architect Enelde",
        "Bookkeeper Molly",
        "Cirwea Strongbow",
        "Flowkeeper Nicyn",
        "Foreman Araz",
        "Gravewalker",
        "Lieutenant Tuffy",
        "Night Terror",
        "The Frantic Construct",
        "Thex Widow",
    },

    ["devastationa"] = {
        "Ailerie the Magnificent",
        "Katog the Deviating",
        "Krynor the Feeder",
        "Soulbright, the Essence of Life",
        "Xywil, the Tree of Life",
    },

    ["skylance"] = {
        "Daosheen the Firstborn",
    },

    ["rage"] = {
        " Restrained Cereton",
        " Vaslaghul Bonelord",
        " The Skulltaker",
        "Yoon the Gleener",
        " Ar`yer the Warlord",
        " Mengalor",
        " Nezark, the Undying Spirit",
        " Jarl Hedmar",
        " Jarl Pinvul",
        " Jarl Ytarin",
        " Savage Fury Grogmaul",
    },

    ["elddar"] = {
        "Animist Yeoh",
        "Cerhan the Wild",
        "Clergyman Jaynen",
        "Geomancer Unala",
        "Loyalist Tobey",
        "Lugnah the Arcane",
        "Strategist Guldar",
        "Trickster Velana",
        "Tunarshen the Free",
        "Vertekin the Soothsayer",
        "Volwen the Unkempt",
    },

    ["takishruinsa"] = {
        "Beau`Draa the false Warden",
        "Fippy Firepaw",
    },

    ["theater"] = {
        "Aesthir the Delusioned",
        "Anastasia the Thought Drinker",
        "Belinda Baleheart",
        "Bleeding Storm",
        "Fangore Boneclaw",
        "Gnarlibramble",
        "Illixis, the Dark Dream",
        "Leafrot",
        "Lilia, the Rancid",
        "Painscreecher",
        "Maestro Tan`lor",
        "Mad Mary-Anne",
        "Master Chrichus",
        "Mistress of Malady",
        "Shatterstyr",
        "Sir Savagery",
        "Talili",
        "The Festering",
        "The Skeletal Steed",
        "Valik the Cruel",
        "Vasella Fireblood",
        "Seraphino the Fierce",
    },

    ["elddara"] = {
        "Guardian of the High Priest",
        "The Night Huntress",
    },

    ["moors"] = {
        "Thunderwood",
    },

    ["mesa"] = {
        "Bashmaker",
        "Bigone",
        "Craita",
        "Incinspaianjen",
        "Manunchi",
        "Nestor",
        "Peretaenu",
        "Mal",
        "Plasa",
        "Schelet",
        "Tarsiit Movila",
        "Ternsmochin",
        "The Fabled Ternsmochin",
        "Uriasarpe",
        "Vorasarpex",
        "Shade of Glenicae",
    },

    ["icefall"] = {
        "Avalanche",
        "Blackfoot",
        "Chief Urgak",
        "Chillbone",
        "Frostpaw",
        "Glacier",
        "Grimjaw",
        "Grock Mist Seer",
        "Ironeyes",
        "Nightmoon Chieftain Blacktooth",
        "Nightmoon Chieftain Snowmane",
        "Taruskor",
        "Tarnuk Farwalker",
    },

    ["sunderock"] = {
        "Darkmist",
        "Fiddleback",
        "Mistwalker",
        "Oblivion",
        "Sulfurog",
        "Whitewater",
        "Wingover",
        "Sentinel of Sunderrock",
    },

    -- NEW ZONES ADDED BELOW

    ["valdeholm"] = {
        "Animal Tender Bealon",
        "Belgar, Captain of the Wall",
        "Drentik the Mad",
        "Fihulf, Hero of the People",
        "Ironbelly",
        "Kangur Vafta Veor",
        "Kellet, Royal Guard Captain",
        "Master Smith Goil",
        "Royal Cryptguard Zerakt",
        "Squad Leader Brontik",
        "Thrymfang",
        "The Void",
        "Watch Commander Cearul",
        "Watch Commander Thellik",
    },

    ["barren"] = {
        "Agrima",
        "Beata the Hag",
        "Captain Nedol Midwater",
        "Mina the Misereable",
        "Prathar the Hunter",
        "Redfoot Pete",
        "Sick Marty",
        "The Fabled Agrima",
        "The Gerratar",
        "Xonda Nelda of Kerrae",
    },

    ["buriedsea"] = {
        "Blacksail Bob",
        "Centehua",
        "Caroline",
        "Dreadclaw",
        "Drowned Pirate Roberts",
        "Friar Jack",
        "Garayy Gali",
        "Garayy Yuundu",
        "Globmogger",
        "Glolden Ghost",
        "Helushka",
        "Iolana the Defender",
        "Lutzan, the Magma Reaver",
        "Manat, Archmage of Redfeather",
        "Rentless Ruth",
        "Shellara Songweaver",
        "Shipwright Barney",
        "Terraraptor",
    },

    ["maidensgrave"] = {
        "Nyxaria, the Abyssal Maiden",
    },

    ["solteris"] = {
        "Stonewatcher of the Ten",
        "Althea",
        "Brenda",
        "Christine",
        "Guardian of the First Prime",
        "Guardian of the Second Prime",
        "Guardian of the Third Prime",
        "Guardian of the Fourth Prime",
        "Guardian of the Fifth Prime",
        "Guardian of the Sixth Prime",
        "Guardian of the Seventh Prime",
        "Guardian of the Eighth Prime",
        "Guardian of the Ninth Prime",
        "Ur-Floxiz Lochmaul",
        "Aprosis the Fourth Confidant",
        "Rear Guard Captain Balreth",
        "Astire, the Lunar Eclipse",
        "Irrissa the Seer",
        "Irrissa the Seer (Clone)",
        "Commodus, Solar Construct",
        "Mayong Mistmoore",
        "Mayong Mistmoore the Darkness",
        "Solusek Ro",
        "Athena",
    },

    ["thalassius"] = {
        "Kraj Iurolapos",
        "Phyrael Mollotus",
        "Rockcrusher",
        "Wavecrasher",
        "Muckdiver",
    },

    ["zhisza"] = {
        "Chitters",
        "Copperfang",
        "Coralitus",
        "Defiler Jaziriiz",
        "Elder Kazzi",
        "Holloweyes",
        "King Brownscale",
        "The Stonecarver",
    },

    ["crystallos"] = {
        "Aerius Windfury",
        "An Elder Earth Drake",
        "Brood Mother Visziaj",
        "Chief Researcher Entharr",
        "Immortal Sentinel of Kerafyrm",
        "Heart of the Avalanche",
        "Icyyr",
        "Keeper of the Stones",
        "Ki`Mrash",
        "Kildrukaun the Ancient Prophet",
        "Kerafyrm the Awakened",
        "Rockcrush",
        "Squire Alkaa",
        "Squire Tectoran",
        "Squire Torrentus",
        "Squire Zirkanamef",
        "The Mightforged Sentinel of Crystallos",
        "Tjudawos the Ancient",
        "Vengeful Captive Elemental",
        "Vengeful Contained Elemental",
        "Zeixshi'Kar",
    },

    -- LDoN 2.0 zones
    ["ruja"] = {
        "a Steelslave Slayer",
        "Baat Groobsmash",
        "Drogar the Indomitable",
        "Golbi the Goblin Patriarch",
        "Sikl the Slayer of Men",
        "Steelslave Brute",
        "Steelslave Crusher",
        "Steelslave Marauder",
        "Steelslave Smasher",
        "Summoran's Uncontrollable Experiment",
        "Tulla Groobsmash",
        "The King of the Ring",
        "Warmistress Skoora",
        "Schagraat",
        "Lurzz",
        "Ugluuk",
        "Huur'Ay",
        "Summoran",
        "Legend of Bloodied Quarries",
    },

    ["mmcd"] = { -- there is a space in front of all of these names.
        " Bloodstice",
        " Count Drakvish",
        " Madame Chiasa",
        " Nightrage Sanguinarch",
        " Scion Radical",
        " Shade of Chiasa",
        " Shade of Sage of Death",
        " The Sage of Death",
        " Trysta the Dark Tutor",
        " Vaelin Grimlore the Dead",
        " The Silent Pianist",
        " Queen Vaelrosa Nyxfang",
    },

    ["taka"] = {
        "The Avatar of Dust",
        "The Desert Treant",
        "Dunebreaker",
        "Flowkeeper Berta",
        "Gravitus Gargantua",
        "Ignatius the Scorched Scarab",
        "Lucinda the Luminous Ladybug",
        "Sandbound Sentinel",
        "Sirocco",
        "Geomancer Blackquill",
    },

    ["mirc"] = {
        "Ancient Amalgam",
        "Ancient Seer Venos",
        "Ancient Warlord Petrad",
        "Avalara Frostgrave",
        "Devouring Vortex",
        "Echo of Synarcana",
        "Enchanted Ice Golem",
        "Frenzied Ice Goblin",
        "Frostfoot Dynamite Master",
        "Mighty White Widow",
        "Nik the Frozen Heroslayer",
        "Skeletal Assassin",
        "Skeletal Champion",
        "Skeletal Fury",
        "Skeletal Monk",
        "Voras the Spider Matriarch",
        "Legend of the Spider Den",
        "Myth of the Spider Den",
        "Black Ice Slime",
    },

}
