return {
    ["qeytoqrg"] = {
        "Gnasher Furgutt",
        "Hadden",
        "Holly Windstalker",
        "Pyzjn",
        "Scruffy",
        "Tovax Vmar",
        "Varsoon",
        "Yollis Jenkins",
    },

    ["oot"] = {
        "A Goblin Headmaster",
        "Allizewsaur",
        "An Ancient Cyclops",
        "Boog Mudtoe",
        "Dixl Drool",
        "Goob Mudtoe",
        "Gornit",
        "Gull Skytalon",
        "Isle Goblin Chieftan",
        "Soarin Brightfeather",
        "Toko Binlittle",
        "a land shark",
        "tainted seafury cyclops",
    },

    ["soldungb"] = {
        "Death Beetle",
        "Efreeti Lord Djarn",
        "Guano Harvester",
        "King Tranix",
        "Kobold Champion",
        "Kobold Noble",
        "Kobold Priest",
        "Lord Nagafen",
        "Magus Rokyl",
        "Noxious Spider",
        "Solusek kobold king",
        "Stone Spider",
        "Warlord Skarlon",
    },

    ["permafrost"] = {
        "A Goblin Archeologist",
        "A Goblin Jailmaster",
        "A Goblin Patriarch",
        "A Goblin Preacher",
        "A Goblin Scryer",
        "An Ice Goblin Alchemist",
        "High Priest Zaharn",
        "King Thex`Ka IV",
        "Lady Vox",
    },

    ["blackburrow"] = {
        "A Giant Plague Rat",
        "A Gnoll Brewer",
        "A Gnoll Commander",
        "A Gnoll Courier",
        "A Gnoll Tactician",
        "Lord Elgnub",
        "Mannan of the Sabertooth",
        "Master Brewer",
        "Refugee Splitpaw",
        "Socho Darkpaw",
        "Splitpaw Commander",
        "The Gnoll High Shaman",
        "Tranixx Darkpaw",
    },

    ["runnyeye"] = {
        "A Pickclaw Crusader",
        "A Slime Elemental",
        "Battlelord Paluk",
        "Battlewizard Unak",
        "Goblin Janitor",
        "Lord Pickclaw",
        "The Sporali Moldmaster",
    },

    ["everfrost"] = {
        "Goblin Diver",
        "Karg IceBear",
        "Redwind",
        "Tainted Wooly Mammoth",
        "Vengeful Composer",
        "Vengeful Lyricist",
        "Vengeful Soloist",
    },

    ["southkarana"] = {
        "Gnashmaw",
        "Gnawfang",
        "Grizzleknot",
        "Groi Gutblade",
        "Knari Morawk",
        "Kroldir Thunderhoof",
        "Marik Clubthorn",
        "Mroon",
        "Narra Tanith",
        "Nisch Val Torash Mashk",
        "Rosch Val L`Vlor",
        "Shaman Lenrel",
        "Shaman Ren`Rex",
        "Synger Foxfyre",
        "Tesch Val Deval`Nmak",
        "Tesch Val Kadvem",
    },

    ["soldunga"] = {
        "CWG Model EXG",
        "Captain Bipnubble",
        "Fire Goblin Bartender",
        "Flame Goblin Foreman",
        "Gabbie Mardoddle",
        "Goblin Drunkard",
        "Goblin High Shaman",
        "Inferno Goblin Captain",
        "Inferno Goblin Torturer",
        "Kindle",
        "Kobold Predator",
        "Lord Gimblox",
        "Lynada the exiled",
        "Reckless Efreeti",
        "Singe",
        "Solusek goblin king",
    },

    ["befallen"] = {
        "Boondin Babbinsbort",
        "Devouring Shadowknight",
        "Dreaded Shadowknight",
        "Enchanted Elf Skeleton",
        "Gynok Moltor",
        "Hateful Shadowknight",
        "Malignant Shadowknight",
        "Priest Amiaz",
        "Soulless Shadowknight",
        "The Thaumaturgist",
        "Zeek`s Shadow",
        "skeleton Lrodd",
    },

    ["oasis"] = {
        "Arthikus",
        "Cazel",
        "Elder Ronin",
        "Hatar",
        "Lockjaw",
        "The Dervish Thug",
    },

    ["cazicthule"] = {
        "Dismay",
        "Dreadfang",
        "Frightchaser",
        "Soul Siphon",
        "Terrorclaw",
        "Toxiferious",
        "a Tae Ew warlord",
        "a Tae Ew warmaster",
    },

    ["crushbone"] = {
        "Ambassador DVinn",
        "Emperor Crush",
        "Lord Darish",
        "Orc Scoutsman",
        "Orc Taskmaster",
        "Orc Thaumaturgist",
        "Orc Warden",
        "The Fabled Ambassador Dvinn",
        "The Fabled Emperor Crush",
        "The Prophet",
    },

    ["guktop"] = {
        "A Froglok Gaz Squire",
        "A Froglok Idealist",
        "A Froglok Realist",
        "A Froglok Scryer",
        "A Froglok Summoner",
        "A Giant Heart Spider",
        "The Froglok Shin Lord",
        "The Froglok Warden",
    },

    ["unrest"] = {
        "A Reanimated Hand",
        "An Undead Barkeep",
        "An Undead Knight of Unrest",
        "Garanel Rucksif",
        "Reclusive Ghoul Magus",
        "Torklar Battlemaster",
    },

    ["hole"] = {
        "Dartain the Lost",
        "Gibartik has",
        "Initiate Sirlis",
        "Irslak the Wretched",
        "Master Yael",
        "Nortlav the Scalekeeper",
        "Rocksoul",
        "Schnozz the Flighty",
        "Slizik the Mighty",
        "Stonesoul the Unmoving",
        "Ulrik the Devout",
    },

    ["gukbottom"] = {
        "A Frenzied Ghoul",
        "A Froglok Crusader",
        "A Froglok Herbalist",
        "A Froglok Noble",
        "A Froglok Tactician",
        "A Ghoul Assassin",
        "A Ghoul Cavalier",
        "A Ghoul Executioner",
        "A Ghoul Ritualist",
        "A Ghoul Sage",
        "A Ghoul Savant",
        "A Ghoul Sentinel",
        "A Ghoul Supplier",
        "A Minotaur Elder",
        "A Minotaur Patriarch",
        "A Reanimated Hand",
        "An Evil Eye",
        "The Ghoul Arch Magus",
        "The Ghoul Lord",
        "the froglok king",
    },

    ["paw"] = {
        "Brother Gruff",
        "Kurrpok Splitpaw",
        "Nisch Val Torash Mashk",
        "Rosch Val L`Vlor",
        "Tesch Val Deval`Nmak",
        "Tesch Val Kadvem",
        "The Ishva Mal",
        "Verishe Mal Executioner",
        "Verishe Mal Judge",
    },

    ["mistmoore"] = {
        "Carmilla",
        "Countess Elizabeth Bathory",
        "Garton Viswin",
        "Lasna Cheroon",
        "Mynthi Davissi",
        "Princess Cherista",
        "William the Bloody",
        "a cloaked dhampyre",
    },

    ["sebilis"] = {
        "Arch Duke Iatol",
        "Baron Yosig",
        "Blood of Chottal",
        "Brogg",
        "Crypt Caretaker",
        "Emperor Chottal",
        "Frenzied Pox Scarab",
        "Froggy",
        "Froglok Armorer",
        "Froglok Armsman",
        "Froglok Bartender",
        "Froglok Chef",
        "Froglok Commander",
        "Froglok Ostiary",
        "Froglok Pickler",
        "Froglok Repairer",
        "Froglok Watcher",
        "Gangrenous Scarab",
        "Gruplinort",
        "Harbinger Freglor",
        "Hierophant Prime Grekal",
        "Myconid Assassin",
        "Myconid Spore King",
        "Sebilite Guardian",
        "Sebilite Protector",
        "The Legendary Trakanon",
        "Tolapumj",
    },

    ["kithicor"] = {
        "Sorrow",
        "Rage",
        "Ecstasy",
        "The Doll Maker",
    },

}
