return {
    ['Modes'] = {
        [1] = 'Tank',
        [2] = 'DPS',
        [3] = 'Healer',
        [4] = 'Hybrid',
    },
    ['ItemSets'] = {
        ['Epic'] = {
            [1] = "Vengeful Taelosian Blood Axe",
            [2] = "Raging Taelosian Alloy Axe",
        },
    },
    ['AbilitySets'] = {
        ['endregen'] = {
            [1] = "Second Wind",
            [2] = "Third Wind",
            [3] = "Fourth Wind",
            [4] = "Respite",
            [5] = "Reprieve",
            [6] = "Rest",
            [7] = "Breather",
            [8] = "Hiatus",
            [9] = "Relax",
            [10] = "Night's Calming",
            [11] = "Convalesce",
        },
        ['beraura'] = {
            [1] = "Aura of Rage",
            [2] = "Bloodlust Aura",
        },
        ['Dicho'] = {
            [1] = "Dichotomic Rage",
            [2] = "Dissident Rage",
            [3] = "Composite Rage",
            [4] = "Ecliptic Rage",

        },
        ['Dfrenzy'] = {
            [1] = "Eviscerating Frenzy",
            [2] = "Heightened Frenzy",
            [3] = "Oppressing Frenzy",
            [4] = "Overpowering Frenzy",
            [5] = "Overwhelming Frenzy",
            [6] = "Conquering Frenzy",
            [7] = "Vanquishing Frenzy",
            [8] = "Demolishing Frenzy",
            [9] = "Mangling Frenzy",
            [10] = "Vindicating Frenzy",
        },
        ['Dvolley'] = {
            [1] = "Rage Volley",
            [2] = "Destroyer's Volley",
            [3] = "Annihilator's Volley",
            [4] = "Decimator's Volley",
            [5] = "Eradicator's Volley",
            [6] = "Savage Volley",
            [7] = "Sundering Volley",
            [8] = "Brutal Volley",
            [9] = "Demolishing Volley",
            [10] = "Mangling Volley",
            [11] = "Vindicating Volley",
            [12] = "Pulverizing Volley",
            [13] = "Eviscerating Volley",
        },
        ['Daxethrow'] = {
            [1] = "Maiming Axe Throw",
            [2] = "Vigorous Axe Throw",
            [3] = "Energetic Axe Throw",
            [4] = "Spirited Axe Throw",
            [5] = "Brutal Axe Throw",
            [6] = "Demolishing Axe Throw",
            [7] = "Mangling Axe Throw",
            [8] = "Vindicating Axe Throw",
            [9] = "Rending Axe Throw",
        },
        ['Daxeof'] = {
            [1] = "Axe of Rallos",
            [2] = "Axe of Graster",
            [3] = "Axe of Illdaera",
            [4] = "Axe of Zurel",
            [5] = "Axe of the Aeons",
            [6] = "Axe of Empyr",
            [7] = "Axe of Derakor",
            [8] = "Axe of Xin Diabo",
            [9] = "Axe of Orrak",
        },
        ['Phantom'] = {
            [1] = "Phantom Assailant",
        },
        ['Alliance'] = {
            [1] = "Demolisher's,",
            [2] = "Mangler's Covenant"  ,
            [3] = "Vindicator's Coalition",
            [4] = "Conqueror's Conjunction",

        },
        ['CheapShot'] = {
            [1] = "Slap in the Face",
            [2] = "Kick in the Teeth",
            [3] = "Punch in The Throat",
            [4] = "Kick in the Shins",
            [5] = "Sucker Punch",
            [6] = "Rabbit Punch",
            [7] = "Swift Punch",
        },
        ['AESlice'] = {
            [1] = "Arcblade",
            [2] = "Arcslice",
            [3] = "Arcsteel",
            [4] = "Arcslash",
            [5] = "Arcshear",
        },
        ['AEVicious'] = {
            [1] = "Vicious Spiral",
            [2] = "Vicious Cyclone",
            [3] = "Vicious Cycle",
            [4] = "Vicious Revolution",
            [5] = "Vicious Whirl",
        },
        ['FrenzyBoost'] = {
            [1] = "Augmented Frenzy",
            [2] = "Amplified Frenzy",
            [3] = "Bolstered Frenzy",
            [4] = "Magnified Frenzy",
            [5] = "Buttressed Frenzy",
            [6] = "Heightened Frenzy",
        },
        ['RageStrike'] = {
            [1] = "Roiling Rage",
            [2] = "Festering Rage",
            [3] = "Bubbling Rage",
            [4] = "Smoldering Rage",
            [5] = "Seething Rage",
            [6] = "Frothing Rage",
        },
        ['SharedBuff'] = {
            [1] = "Shared Barbarism",
            [2] = "Shared Bloodlust",
            [3] = "Shared Brutality",
            [4] = "Shared Savagery",
            [5] = "Shared Viciousness",
            [6] = "Shared Cruelty",
            [7] = "Shared Ruthlessness",
            [8] = "Shared Atavism",
            [9] = "Shared Violence",
        },
        ['PrimaryBurnDisc'] = {
            [1] = "Berserking Discipline",
            [2] = "Sundering Discipline",
            [3] = "Brutal Discipline",
        },
        ['CleavingDisc'] = {
            [1] = "Cleaving Rage Discipline",
            [2] = "Cleaving Anger Discipline",
            [3] = "Cleaving Acrimony Discipline",
        },
        ['FlurryDisc'] = {
            [1] = "Vengeful Flurry Discipline",
            [2] = "Avenging Flurry Discipline",
        },
        ['DisconDisc'] = {
            [1] = "Disconcerting Discipline",
        },
        ['ResolveDisc'] = {
            [1] = "Frenzied Resolve Discipline",
        },
        ['HHEBuff'] = {
            [1] = "Battle Cry",
            [2] = "War Cry",
            [3] = "Battle Cry of Dravel",
            [4] = "War Cry of Dravel",
            [5] = "Battle Cry of the Mastruq",
            [6] = "Ancient: Cry of Chaos",
        },
        ['CryDmg'] = {
            [1] = "Cry Havoc",
            [2] = "Cry Carnage",
        },
        ['AutoAxe'] = {
            [1] = "Corroded Axe",
            [2] = "Blunt Axe",
            [3] = "Steel Axe",
            [4] = "Bearded Axe",
            [5] = "Mithril Axe",
            [6] = "Balanced War Axe",
            [7] = "Bonesplicer Axe",
            [8] = "Fleshtear Axe",
            [9] = "Cold Steel Cleaving Axe",
            [10] = "Mithril Bloodaxe",
            [11] = "Rage Axe",
            [12] = "Bloodseeker's Axe",
            [13] = "Battlerage Axe",
            [14] = "Deathfury Axe",
            [15] = "Tainted Axe of Hatred",
            [16] = "Axe of The Destroyer",
            [17] = "Axe of The Annihilator",
            [18] = "Axe of The Decimator",
            [19] = "Axe of The Eradicator",
            [20] = "Axe of The Savage",
            [21] = "Axe of the Sunderer",
            [22] = "Axe of The Brute",
            [23] = "Axe of The Demolisher",
            [24] = "Axe of The Mangler",
            [25] = "Axe of The Vindicator",
            [26] = "Axe of the Conqueror",
            [27] = "Axe of the Eviscerator",
        },
        ['DichoAxe'] = {
            [1] = "Axe of The Demolisher",
            [2] = "Axe of The Mangler",
            [3] = "Axe of the Conqueror",
        },
        ['Tendon'] = {
            [1] = "Tendon Slice",
            [2] = "Tendon Shred",
            [3] = "Tendon Cleave",
            [4] = "Tendon Sever",
            [5] = "Tendon Shear",
            [6] = "Tendon Lacerate",
            [7] = "Tendon Slash",
            [8] = "Tendon Gash",
            [9] = "Tendon Tear",
            [10] = "Tendon Rupture",
            [11] = "Tendon Rip",
        },
        ['SappingStrike'] = {
            [1] = "Sapping Strikes",
            [2] = "Shriveling Strikes",
        },
        ['ReflexDisc'] = {
            [1] = "Reflexive Retaliation",
            [2] = "Instinctive Retaliation",
        },
        ['RestFrenzy'] = {
            [1] = "Desperate Frenzy",
            [2] = "Blinding Frenzy",
            [3] = "Restless Frenzy",

        },
        ['RetaliationDodge'] = {
            [1] = "Preemptive Retaliation",
            [2] = "Primed Retaliation" ,
            [3] = "Premature Retaltion",
            [4] = "Proactive Retaliation",
            [5] = "Prior Retaliation"  ,
            [6] = "Advanced Retaliation",
            [7] = "Early Retaliation",
        },
        ['TempleStun'] = {
            [1] = "Temple Shatter",
            [2] = "Temple Bash",
            [3] = "Temple Blow",
            [4] = "Temple Chop",
            [5] = "Temple Crack",
            [6] = "Temple Crush",
            [7] = "Temple Demolish",
            [8] = "Temple Shatter",
            [9] = "Temple Slam",
            [10] = "Temple Smash",
            [11] = "Temple Strike",
        },
        ['JarringStrike'] = {
            [1]  = "Jarring Crash",
            [2]  = "Jarring Strike",
            [3]  = "Jarring Smash",
            [4]  = "Jarring Clash",
            [5]  = "Jarring Slam",
            [6]  = "Jarring Blow",
            [7]  = "Jarring Crush",
            [8]  = "Jarring Smite",
            [9]  = "Jarring Jolt",
            [10] = "Jarring Shock",
            [11] = "Jarring Impact",
        },
    },
    ['Rotations'] = {
        ['Tank'] = {
            ["Available"] = 0,
            ['Combat'] = {},
            ['Downtime'] = {},
            ['Burn'] = {},
        },
        ['DPS'] = {
            ["Available"] = 1,
            ['Combat'] = {},
            ['Downtime'] = {},
            ['Burn'] = {},
        },
        ['Healer'] = { 
            ["Available"] = 0,
            ['Combat'] = {},
            ['Downtime'] = {},
            ['Burn'] = {},
        },
        ['Hybrid'] = { 
            ["Available"] = 0,
            ['Combat'] = {},
            ['Downtime'] = {},
            ['Burn'] = {},
        },
    },
    ['DefaultConfig'] = {
        ['Mode'] = '2',
    },
},