return {
    ['Modes'] = {
        ['Heal'] = 0,
        ['Mana'] = 1,
        ['TLP'] = 2,
        ['DPS'] = 99,
    },
    ['ItemSets'] = {
        ['Epic'] = {
            [1] = "Staff of Living Brambles",
            [2] = "Staff of Everliving Brambles",
        },
    },
    ['AbilitySets'] = {
        ['Alliance'] = {
            --, Buff >= LVL102
            [1] = "Bosquetender's,",
            [2] = "Arbor Tender's Coalition",
            [3] = "Arboreal Atonement",

        },
        ['FireAura'] = {
            -- Spell Series >= 87LVL Minimum
            [1] = "Wildspark Aura",
            [2] = "Wildblaze Aura",
            [3] = "Wildfire Aura",
        },
        ['IceAura'] = {
            -- Spell Series >= 88LVL Minimum -- Only Heroic Aura that will be used
            [1] = "Icerend Aura",
            [2] = "Frostreave Aura",
            [3] = "Frostweave Aura",
            [4] = "Frostone Aura",
            [5] = "Frostcloak Aura",
            [6] = "Frostfell Aura",
            [7] = "Nightchill Aura",
        },
        ['HealingAura'] = {
            -- Healing Aura >= 55
            [1] = "Aura of Life",
            [2] = "Aura of the Grove",
        },
        ['SingleTgtCure'] = {
            -- Single Target Multi-Cure >= 84
            [1] = "Expurgated Blood",
            [2] = "Unblemished Blood",
            [3] = "Cleansed Blood",
            [4] = "Perfected Blood",
            [5] = "Purged Blood",
            [6] = "Purified Blood",
            [7] = "Sanctified Blood",
        },
        ['GroupCure'] = {
            -- Group Multi-Cure >=91
            [1] = "Wildtender's Breeze",
            [2] = "Copsetender's Breeze",
            [3] = "Bosquetender's Breeze",
            [4] = "Fawnwalker's Breeze",
            [5] = "Nightwhisper's Breeze",
        },
        ['QuickHealSurge'] = {
            -- Main Quick heal >=75
            [1] = "Adrenaline Deluge",
            [2] = "Adrenaline Barrage",
            [3] = "Adrenaline Torrent",
            [4] = "Adrenaline Rush",
            [5] = "Adrenaline Flood",
            [6] = "Adrenaline Blast",
            [7] = "Adrenaline Burst",
            [8] = "Adrenaline Swell",
            [9] = "Adrenaline Surge",
            [10] = "Adrenaline Spate",
        },
        ['QuickHeal'] = {
            -- Backup Quick heal >= LVL90
            [1] = "Rejuvenescence",
            [2] = "Revitalization",
            [3] = "Resurgence",
            [4] = "Vivification",
            [5] = "Invigoration",
            [6] = "Rejuvilation",
            [7] = "Sootheseance",
        },
        ['LongHeal'] = {
            -- Long Heal >= 1 -- skipped 10s cast heals.
            [1] = "Clotavida",
            [2] = "Viridavida",
            [3] = "Curavida",
            [4] = "Panavida",
            [5] = "Sterivida",
            [6] = "Sanavida",
            [7] = "Benevida",
            [8] = "Granvida",
            [9] = "Puravida",
            [10] = "Pure Life",
            [11] = "Chlorotrope",
            [12] = "Sylvan Infusion",
            [13] = "Nature's Infusion",
            [14] = "Nature's Touch",
            [15] = "Chloroblast",
            [16] = "Forest's Renewal",
            [17] = "Superior Healing",
            [18] = "Nature's Renewal",
            [19] = "Healing Water",
            [20] = "Greater Healing",
            [21] = "Healing",
            [22] = "Light Healing",
            [23] = "Minor Healing",
        },
        ['QuickGroupHeal'] = {
            -- Quick Group heal >= LVL78
            [1] = "Survival of the Favored",
            [2] = "Survival of the Auspicious",
            [3] = "Survival of the Serendipitous",
            [4] = "Survival of the Fortuitous",
            [5] = "Survival of the Prosperous",
            [6] = "Survival of the Propitious",
            [7] = "Survival of the Felicitous",
            [8] = "Survival of the Fittest",
            [9] = "Survival of the Unrelenting"
        },
        ['LongGroupHeal'] = {
            -- Long Group heal >= LVL 70
            [1] = "Lunalesce",
            [2] = "Lunasalve",
            [3] = "Lunasoothe",
            [4] = "Lunassuage",
            [5] = "Lunalleviation",
            [6] = "Lunamelioration",
            [7] = "Lunulation",
            [8] = "Crescentbloom",
            [9] = "Lunarlight",
            [10] = "Moonshadow",
            [11] = "Lunarush",           
        },
        ['PromHeal'] = {
            -- Promised Heals Line Druid
            [1] = "Promised Reknit",
            [2] = "Promised Replenishment",
            [3] = "Promised Revitalization",
            [4] = "Promised Recovery",
            [5] = "Promised Regeneration",
            [6] = "Promised Rebirth",
            [7] = "Promised Refreshment",
            [8] = "Promised Revivification",
        },
        ['FrostDebuff'] = {
            -- Frost Debuff Series -- >= 74LVL -- On Bar
            [1] = "Restless Frost",
            [2] = "Glistening Frost",
            [3] = "Moonbright Frost",
            [4] = "Lustrous Frost",
            [5] = "Silver Frost",
            [6] = "Argent Frost",
            [7] = "Blanched Frost",
            [8] = "Gelid Frost",
            [9] = "Hoar Frost",
            [10] = "Primal Frost",
        },
        ['RoDebuff'] = {
            -- Ro Debuff Series -- >= 37LVL -- AA Starts at LVL (Single Target) -- On Bar Until AA
            [1] = "Clasp of Ro",
            [2] = "Cowl of Ro",
            [3] = "Crush of Ro",
            [4] = "Cowl of Ro",
            [5] = "Clutch of Ro",
            [6] = "Grip of Ro",
            [7] = "Grasp of Ro",
            [8] = "Sun's Corona",
            [9] = "Ro's Illumination",
            [10] = "Ro's Smoldering Disjunction",
            [11] = "Fixation of Ro",
            [12] = "Ro's Fiery Sundering",
            [13] = "Cinch of Ro",
        },
        ['RoDebuffAE'] = {
            -- Ro AE Debuff Series -- >= 97LVL -- AA Starts at LVL
            [1] = "Glare of Ro",
            [2] = "Gaze of Ro",
            [3] = "Column of Ro",
            [4] = "Pillar of Ro",
            [5] = "Scrutiny of Ro",
        },
        ['IceBreathDebuff'] = {
            -- Ice Breath Series >= 63LVL -- On Bar
            [1] = "Icerend Breath",
            [2] = "Frostreave Breath",
            [3] = "Blizzard Breath",
            [4] = "Frosthowl Breath",
            [5] = "Encompassing Breath",
            [6] = "Bracing Breath",
            [7] = "Coldwhisper Breath",
            [8] = "Chillvapor Breath",
            [9] = "Icefall Breath",
            [10] = "Glacier Breath",
            [11] = "E`ci's Frosty Breath",
            [12] = "Twilight Breath",
        },
        ['SkinDebuff'] = {
            -- Skin Debuff Series >= 73LVL -- On Bar
            [1] = "Skin to Sumac",
            [2] = "Skin to Seedlings",
            [3] = "Skin to Foliage",
            [4] = "Skin to Leaves",
            [5] = "Skin to Flora",
            [6] = "Skin to Mulch",
            [7] = "Skin to Vines",
            [8] = "Skin to Lichen"
        },
        ['ReptileCombatInnate'] = {
            -- Reptile Combat Innate >= 68LVL -- On Bar
            [1] = "Defense of the Reptile",
            [2] = "Guard of the Reptile",
            [3] = "Pellicle of the Reptile",
            [4] = "Husk of the Reptile",
            [5] = "Hide of the Reptile",
            [6] = "Shell of the Reptile",
            [7] = "Carapace of the Reptile",
            [8] = "Scales of the Reptile",
            [9] = "Skin of the Reptile",
            [10] = "Bulwark of the Reptile",
        },
        ['NaturesWrathDOT'] = {
            -- Natures Wrath DOT Line >= 75LVL -- On Bar
            [1] = "Nature's Fervid Wrath",
            [2] = "Nature's Blistering Wrath",
            [3] = "Nature's Fiery Wrath",
            [4] = "Nature's Withering Wrath",
            [5] = "Nature's Scorching Wrath",
            [6] = "Nature's Incinerating Wrath",
            [7] = "Nature's Searing Wrath",
            [8] = "Nature's Burning Wrath",
            [9] = "Nature's Blazing Wrath",
            [10] = "Nature's Sweltering Wrath",
        },
        ['HordeDOT'] = {
            -- Horde Dots >= 10LVL -- On Bar
            [1] = "Horde of Duskwigs",
            [2] = "Horde of Hyperboreads",
            [3] = "Horde of Polybiads",
            [4] = "Horde of Aculeids",
            [5] = "Horde of Mutillids",
            [6] = "Horde of Vespids",
            [7] = "Horde of Scoriae",
            [8] = "Horde of the Hive",
            [9] = "Horde of Fireants",
            [10] = "Swarm of Fireants",
            [11] = "Wasp Swarm",
            [12] = "Swarming Death",
            [13] = "Winged Death",
            [14] = "Drifting Death",
            [15] = "Drones of Doom",
            [16] = "Creeping Crud",
            [17] = "Stinging Swarm",
        },
        ['SunDOT'] = {
            -- SUN Dot Line >= 49LVL -- On Bar
            [1] = "Sunpyre",
            [2] = "Sunshock",
            [3] = "Sunflame",
            [4] = "Sunflash",
            [5] = "Sunblaze",
            [6] = "Sunscorch",
            [7] = "Sunbrand",
            [8] = "Sunsinge",
            [9] = "Sunsear",
            [10] = "Sunscorch",
            [11] = "Vengeance of the Sun",
            [12] = "Vengeance of Tunare",
            [13] = "Vengeance of Nature",
            [14] = "Vengeance of the Wild",
        },
        ['SunrayDOT'] = {
            -- Sunray Line >= 1 LVL
            [1] = "Tenebrous Sunray",
            [2] = "Erupting Sunray",
            [3] = "Overwhelming Sunray",
            [4] = "Consuming Sunray",
            [5] = "Incinerating Sunray",
            [6] = "Blazing Sunray",
            [7] = "Scorching Sunray",
            [8] = "Withering Sunray",
            [9] = "Torrid Sunray",
            [10] = "Blistering Sunray",
            [11] = "Immolation of the Sun",
            [12] = "Sylvan Embers",
            [13] = "Immolation of Ro",
            [14] = "Breath of Ro",
            [15] = "Immolate",
            [16] = "Flame Lick",
        },
        ['MoonBeamDOT'] = {
            -- MoonBeam Dot
            [1] = "Gelid Moonbeam",
            [2] = "Algid Moonbeam",
            [3] = "Frigid Moonbeam",
            [4] = "Argent Moonbeam",
            [5] = "Pearlescent Moonbeam",
            [6] = "Opaline Moonbeam",
            [7] = "Onyx Moonbeam",
        },
        ['RemoteMoonDD'] = {
            -- Remote Moon DD >= 99LVL
            [1] = "Remote Moonchill",
            [2] = "Remote Moonrake",
            [3] = "Remote Moonflash",
            [4] = "Remote Moonflame",
            [5] = "Remote Moonfire",
        },
        ['RemoteSunDD'] = {
            -- Remote Sun DD >= 83LVL
            [1] = "Remote Sunbolt",
            [2] = "Remote Sunshock",
            [3] = "Remote Sunblaze",
            [4] = "Remote Sunflash",
            [5] = "Remote Sunfire",
            [6] = "Remote Sunburst",
            [7] = "Remote Sunflare",
            [8] = "Remote Manaflux",
        },
        ['RoarDD'] = {
            -- Roar DD >= 93LVL
            [1] = "Bloody Roar",
            [2] = "Typhonic Roar",
            [3] = "Cyclonic Roar",
            [4] = "Anabatic Roar",
            [5] = "Katabatic Roar",
            [6] = "Roar of Kolos",            
        },
        ['QuickRoarDD'] = {
            -- Quick Cast Roar Series -- will be replaced by roar at lvl 93
            [1] = "Maelstrom of the Stormborn",
            [2] = "Thunderbolt of the Stormborn",
            [3] = "Typhoon of the Stormborn",
            [4] = "Whirlwind of the Stormborn",
            [5] = "Cyclone of the Stormborn",
            [6] = "Shear of the Stormborn",
            [7] = "Squall of the Stormborn",
            [8] = "Tempest of the Stormborn",
            [9] = "Gale of the Stormborn",
            [10] = "Stormwatch",
            [11] = "Storm's Fury",
            [12] = "Dustdevil",
            [13] = "Fury of Air",            
        },
        ['DichoSpell'] = {
            -- Dicho Spell >= 101LVL
            [1] = "Ecliptic Winds",
            [2] = "Composite Winds",
            [3] = "Dissident Winds",
            [4] = "Dichotomic Winds",            
        },
        ['WinterFireDD'] = {
            -- Winters Fire DD Line >= 73LVL -- Using for Low level Fire DD as well
            [1] = "Winter's Wildbrume",
            [2] = "Winter's Wildshock",
            [3] = "Winter's Wildblaze",
            [4] = "Winter's Wildflame",
            [5] = "Winter's Wildfire",
            [6] = "Winter's Sear",
            [7] = "Winter's Pyre",
            [8] = "Winter's Flare",
            [9] = "Winter's Blaze",
            [10] = "Winter's Flame",
            [11] = "Solstice Strike",
            [12] = "Sylvan Fire",
            [13] = "Summer's Flame",    
            [14] = "Wildfire",
            [15] = "Scoriae",
            [16] = "Starfire",      
            [17] = "Firestrike",
            [18] = "Combust",
            [19] = "Ignite", 
            [20] = "Burst of Fire",
            [21] = "Burst of Flame",             
        },
        ['ChillDOT'] = {
            -- Chill DOT Line -- >= 95LVL -- Used for Burns
            [1] = "Chill of the Dusksage Tender",
            [2] = "Chill of the Arbor Tender",
            [3] = "Chill of the Wildtender",
            [4] = "Chill of the Copsetender",
            [5] = "Chill of the Visionary",
            [6] = "Chill of the Natureward",            
        },
        ['RootSpells'] = {
            -- Root Spells
            [1] = "Vinelash Assault",
            [2] = "Vinelash Cascade",
            [3] = "Spore Spiral",
            [4] = "Savage Roots",
            [5] = "Earthen Roots",
            [6] = "Entrapping Roots",
            [7] = "Engorging Roots",
            [8] = "Engulfing Roots",
            [9] = "Enveloping Roots",
            [10] = "Ensnaring Roots",
            [11] = "Grasping Roots",            
        },
        ['SnareSpells'] = {
            -- Snare Spells
            [1] = "Thornmaw Vines",
            [2] = "Hungry Vines",
            [3] = "Serpent Vines",
            [4] = "Entangle",
            [5] = "Mire Thorns",
            [6] = "Bonds of Tunare",
            [7] = "Ensnare",
            [8] = "Snare",
            [9] = "Tangling Weeds",            
        },
        ['TwincastNuke'] = {
            -- Druid Twincast
            [1] = "Sundew Blessing",
            [2] = "Sunrise Blessing",
            [3] = "Sunbreeze Blessing",
            [4] = "SunBeam Blessing",
            [5] = "SunFire Blessing",
            [6] = "SunFlash Blessing",
            [7] = "SunRake Blessing",
            [8] = "Sunwarmth Blessing",            
        },
        ['IceNuke'] = {
            --Ice Nuke
            [1] = "Ice",
            [2] = "Frost",
            [3] = "Moonfire",
            [4] = "Winter's Frost",
            [5] = "Glitterfrost",
            [6] = "Rime Crystals",
            [7] = "Hoar Crystals",
            [8] = "Glaciating Crystals",
            [9] = "Argent Crystals",
            [10] = "Sterlingfrost Crystals",
            [11] = "Gelid Crystals",
            [12] = "Frostweave Crystals",
            [13] = "Frostreave Crystals",
            [14] = "Icerend Crystals",
            [15] = "Moonwhisper Crystals",            
        },
        ['IceRainNuke'] = {
            [1] = "Cascade of Hail",
            [2] = "Pogonip",
            [3] = "Avalanche",
            [4] = "Blizzard",
            [5] = "Winter's Storm",
            [6] = "Tempest Wind",
            [7] = "Cloudburst Hail",
            [8] = "Torrential Hail",
            [9] = "Cascading Hail",
            [10] = "Cyclonic Hail",
            [11] = "Crashing Hail",
            [12] = "Hailstorm",
            [13] = "Plummeting Hail",
            [14] = "Plunging Hail",
            [15] = "Tempestuous Hail",            
        },
        ['ShroomPet'] = {
            --Druid Mushroom DOT Pet Line >= 84LVL --used for mana savings
            [1] = "Saprophyte Assault",
            [2] = "Chytrid Assault",
            [3] = "Fungusoid Assault",
            [4] = "Sporali Storm",
            [5] = "Sporali Assault",
            [6] = "Myconid Assault",
            [7] = "Polyporous Assault",
            [8] = "Blast of Hypergrowth",            
        },
        ['IceDD'] = {
            -- Ice Nuke DD --Gap Filler
            [1] = "Moonfire",
            [2] = "Frost",            
        },
        ['RemoteDD'] = {
            -- Spell vars Added for Bobcatts New Mode.While keeping originals Intact! for other modes.
            [1] = "Remote Moonrake",
            [2] = "Remote Sunshock",
            [3] = "Remote Moonflash",
            [4] = "Remote Sunblaze",
            [5] = "Remote Moonflame",
            [6] = "Remote Sunflash",
            [7] = "Remote Moonfire",
            [8] = "Remote Sunfire",
            [9] = "Remote Sunburst",
            [10] = "Remote Sunflare",
            [11] = "Remote Manaflux",            
        },
        ['SunMoonDot'] = {
            --, Line >= 1 LVL
            [1] = "Opaline Moonbeam",
            [2] = "Erupting Sunray",
            [3] = "Pearlescent Moonbeam",
            [4] = "Overwhelming Sunray",
            [5] = "Argent Moonbeam",
            [6] = "Consuming Sunray",
            [7] = "Frigid Moonbeam",
            [8] = "Incinerating Sunray",
            [9] = "Algid Moonbeam",
            [10] = "Blazing Sunray",
            [11] = "Gelid Moonbeam",
            [12] = "Scorching Sunray",
            [13] = "Withering Sunray",
            [14] = "Torrid Sunray",
            [15] = "Blistering Sunray",
            [16] = "Immolation of the Sun",
            [17] = "Sylvan Embers",
            [18] = "Immolation of Ro",
            [19] = "Breath of Ro",
            [20] = "Immolate",
            [21] = "Flame Lick",
        },
        ['SelfShield'] = {
            -- Self Shield Buff
            [1] = "Shadespine Coat",
            [2] = "Icebriar Coat",
            [3] = "Daggerspike Coat",
            [4] = "Daggerspur Coat",
            [5] = "Spikethistle Coat",
            [6] = "Spineburr Coat",
            [7] = "Bonebriar Coat",
            [8] = "Brierbloom Coat",
            [9] = "Viridithorn Coat",
            [10] = "Viridicoat",
            [11] = "Nettlecoat",
            [12] = "Brackencoat",
            [13] = "Bladecoat",
            [14] = "Thorncoat",
            [15] = "Spikecoat",
            [16] = "Bramblecoat",
            [17] = "Barbcoat",
            [18] = "Thistlecoat",           
        },
        ['SelfManaRegen'] = {
            -- Self mana Regen Buff
            [1] = "Mask of the Dusksage Tender",
            [2] = "Mask of the Arbor Tender",
            [3] = "Mask of the Wildtender",
            [4] = "Mask of the Copsetender",
            [5] = "Mask of the Bosquetender",
            [6] = "Mask of the Thicket Dweller",
            [7] = "Mask of the Arboreal",
            [8] = "Mask of the Raptor",
            [9] = "Mask of the Shadowcat",
            [10] = "Mask of the Wild",
            [11] = "Mask of the Forest",
            [12] = "Mask of the Hunter",
            [13] = "Mask of the Stalker",            
        },
        ['HPTypeOneGroup'] = {
            -- Opaline Group Health
            [1] = "Luclinite Blessing",
            [2] = "Opaline Blessing",
            [3] = "Arcronite Blessing",
            [4] = "Shieldstone Blessing",
            [5] = "Granitebark Blessing",
            [6] = "Stonebark Blessing",
            [7] = "Blessing of the Timbercore",
            [8] = "Blessing of the Heartwood",
            [9] = "Blessing of the Ironwood",
            [10] = "Blessing of the Direwild",
            [11] = "Blessing of Steeloak",
            [12] = "Blessing of the Nine",
            [13] = "Protection of the Glades",
            [14] = "Protection of Nature",
            [15] = "Protection of Diamond",
            [16] = "Protection of Steel",
            [17] = "Protection of Rock",
            [18] = "Protection of Wood",           
        },
        ['TempHPBuff'] = {
            -- Temp Health -- Focus on Tank
            [1] = "Fervent Growth",
            [2] = "Frenzied Growth",
            [3] = "Savage Growth",
            [4] = "Ferocious Growth",
            [5] = "Rampant Growth",
            [6] = "Unfettered Growth",
            [7] = "Untamed Growth",
            [8] = "Wild Growth",
        },
        ['GroupRegenBuff'] = {
            -- Group Regen BuffAll Have Long Duration HP Regen Buffs. Not Short term Heal.
            [1] = "Talisman of the Tenacious",
            [2] = "Talisman of the Enduring",
            [3] = "Talisman of the Unwavering",
            [4] = "Talisman of the Faithful",
            [5] = "Talisman of the Steadfast",
            [6] = "Talisman of the Indomitable",
            [7] = "Talisman of the Relentless",
            [8] = "Talisman of the Resolute",
            [9] = "Talisman of the Stalwart", 
            [10] = "Pack Regeneration",
            [11] = "Pack Chloroplast",
            [12] = "Regrowth of the Grove" ,
            [13] = "Blessing of Oak" ,
            [14] = "Blessing of Replenishment",
        },
        ['AtkBuff'] = {
            -- Single Target Attack Buff for MeleeGuard
            [1] = "Mammoth's Force",
            [2] = "Mammoth's Strength",
            [3] = "Lion's Strength",
            [4] = "Nature's Might",
            [5] = "Girdle of Karana",
            [6] = "Storm Strength",
            [7] = "Strength of Stone",
            [8] = "Strength of Earth",            
        },
        ['GroupDmgShield'] = {
            -- Group Damage Shield -- Focus on the tank
            [1] = "Legacy of Icebriars",
            [2] = "Legacy of Daggerspikes",
            [3] = "Legacy of Daggerspurs",
            [4] = "Legacy of Spikethistles",
            [5] = "Legacy of Spineburrs",
            [6] = "Legacy of Bonebriar",
            [7] = "Legacy of Brierbloom",
            [8] = "Legacy of Viridithorns",
            [9] = "Legacy of Viridiflora",
            [10] = "Legacy of Nettles",
            [11] = "Legacy of Bracken",
            [12] = "Legacy of Thorn",
            [13] = "Legacy of Spike",
            -- Group Damage Shield -- Combined all single and group dammage shields.
            [14] = "Legacy of Bloodspikes",
            [15] = "Duskthorn",
            [16] = "Legacy of Icebriars",
            [17] = "Icebriar Bulwark",
            [18] = "Legacy of Daggerspikes",
            [19] = "Daggerspike Bulwark",
            [20] = "Legacy of Daggerspurs",
            [21] = "Daggerspur Bulwark",
            [22] = "Legacy of Spikethistles",
            [23] = "Spikethistle Bulwark",
            [24] = "Legacy of Spineburrs",
            [25] = "Spineburr Bulwark",
            [26] = "Legacy of Bonebriar",
            [27] = "Bonebriar Bulwark",
            [28] = "Legacy of Brierbloom",
            [29] = "Brierbloom Bulwark",
            [30] = "Legacy of Viridithorns",
            [31] = "Viridifloral Bulwark",
            [32] = "Legacy of Viridiflora",
            [33] = "Viridifloral Shield",
            [34] = "Legacy of Nettles",
            [35] = "Nettle Shield",
            [36] = "Legacy of Bracken",
            [37] = "Shield of Bracken",
            [38] = "Legacy of Thorn",
            [39] = "Shield of Blades",
            [40] = "Legacy of Spike",
            [41] = "Shield of Thorns",
            [42] = "Shield of Spikes",
            [43] = "Shield of Brambles",
            [44] = "Shield of Barbs",
            [45] = "Shield of Thistles",            
        },
        ['MoveSpells'] = {
            -- Group Movement Series Spells -- Mix of group target and single target but will require the same dannet checks
            [1] = "Flight of Falcons",
            [2] = "Flight of Eagles",
            -- [] = "Spirit of Scale",
            [3] = "Feral Pack",
            [4] = "Share Form of the Great Wolf",
            [5] = "Pack Shrew",
            [6] = "Pack Spirit",
            [7] = "Share Wolf Form",
            [8] = "Spirit of Falcons",
            [9] = "Spirit of Eagle",
            [10] = "Spirit of the Shrew",
            -- [] = "Scale of Wolf",
            [11] = "Spirit of Wolf",            
        },
        ['ManaBear'] = {
            --Druid Mana Bear Growth Line
            -- [] = "Nature Walker's Behest",
            [1] = "Nurturing Growth",
            [2] = "Nourishing Growth",
            [3] = "Sustaining Growth",
            [4] = "Bolstered Growth",            
        },
        ['SingleDS'] = {
            --Single Target Damage Shield
            [1] = "Shield of Thistles",
            [2] = "Shield of Barbs",
            [3] = "Shield of Brambles",
            [4] = "Shield of Spikes",
            [5] = "Shield of Thorns",
            [6] = "Shield of Blades",
            [7] = "Shield of Bracken",
            [8] = "Nettle Shield",
            [9] = "Viridifloral Shield",
            [10] = "Viridifloral Bulwark",
            [11] = "Brierbloom Bulwark",
            [12] = "Bonebriar Bulwark",
            [13] = "Spineburr Bulwark",
            [14] = "Spikethistle Bulwark",
            [15] = "Daggerspur Bulwark",
            [16] = "Daggerspike Bulwark",
            [17] = "Icebriar Bulwark",
        },
    },
    ['Rotations'] = {
        ['Tank'] = {
            ['Active'] = 1,
            ['Downtime'] = 1,
            ['Burn'] = 1,
        },
        ['DPS'] = {
            ['Ative'] = 1,
            ['Downtime'] = 1,
            ['Burn'] = 1,
        },
        ['TLP'] = {
            ['TLPTank'] = 1,
            ['TLPDPSHeal'] = 1,
            ['TLPDowntime'] = 1,
            ['TLPBurn'] = 1,
        },
    },

    ['DefaultConfig'] = {
        ['Mode'] = 'Tank',
    },
}



