local mq          = require('mq')
local RGMercUtils = require("utils.rgmercs_utils")

return {
    ['Modes'] = {
        ['Tank'] = 0,
        ['DPS'] = 1,
        ['TLP'] = 2,
    },
    ['ItemSets'] = {
        ['Epic'] = {
            [1] = "Deathwhisper",
            [2] = "Soulwhisper",
        },
    },
    ['AbilitySets'] = {
        ['SelfHPBuff'] = {
            [1] = "Shield of Shadow",
            [2] = "Shield of Restless Ice",
            [3] = "Shield of Scales",
            [4] = "Shield of the Pellarus",
            [5] = "Shield of the Dauntless",
            [6] = "Shield of Bronze",
            [7] = "Shield of Dreams",
            [8] = "Shield of the Void",
            [9] = "Bulwark of the Crystalwing",
            [10] = "Shield of the Crystalwing",
            [11] = "Ether Shield",
            [12] = "Shield of Maelin",
            [13] = "Shield of the Arcane",
            [14] = "Shield of the Magi",
            [15] = "Arch Shielding",
            [16] = "Greater Shielding",
            [17] = "Major Shielding",
            [18] = "Shielding",
            [19] = "Lesser Shielding",
        },
        ['SelfRune1'] = {
            [1] = "Carrion Skin",
            [2] = "Frozen Skin",
            [3] = "Ashen Skin",
            [4] = "Deadskin",
            [5] = "Zombieskin",
            [6] = "Ghoulskin",
            [7] = "Grimskin",
            [8] = "Corpseskin",
            [9] = "Shadowskin",
            [10] = "Wraithskin",
        },
        ['SelfSpellShield1'] = {
            [1] = "Shield of Inevitability",
            [2] = "Shield of Destiny",
            [3] = "Shield of Order",
            [4] = "Shield of Consequence",
            [5] = "Shield of Fate",
        },
        ['FDSpell'] = {
            -- Fd Spell
            [1] = "Death Peace",
        },

        ---DPS
        ['AllianceSpell'] = {
            -- Alliance Spells
            [1] = "Malevolent Alliance",
            [2] = "Malevolent Covenant",
            [3] = "Malevolent Coalition",
            [4] = "Malevolent Conjunction",
        },
        ['DichoSpell'] = {
            ---DichoSpell >= LVL101
            [1] = "Ecliptic Paroxysm",
            [2] = "Composite Paroxysm",
            [3] = "Dissident Paroxysm",
            [4] = "Dichotomic Paroxysm",
        },
        ['SwarmPet'] = {
            ---SwarmPet >= LVL85
            [1] = "Call Skeleton Mass",
            [2] = "Call Skeleton Horde",
            [3] = "Call Skeleton Army",
            [4] = "Call Skeleton Mob",
            [5] = "Call Skeleton Throng",
            [6] = "Call Skeleton Host",
            [7] = "Call Skeleton Crush",
            [8] = "Call Skeleton Swarm",
        },
        ['HealthTaps'] = {
            ---HealthTaps >= LVL1
            [1] = "Soulflay",
            [2] = "Soulgouge",
            [3] = "Draw Essence",
            [4] = "Soulsiphon",
            [5] = "Consume Essence",
            [6] = "Soulrend",
            [7] = "Hemorrhage Essence",
            [8] = "Plunder Essence",
            [9] = "Bleed Essence",
            [10] = "Divert Essence",
            [11] = "Drain Essence",
            [12] = "Siphon Essence",
            [13] = "Drain Life",
            -- [] =["Ancient: Touch of Orshilak",
            [14] = "Soulspike",
            [15] = "Touch of Mujaki",
            [16] = "Touch of Night",
            [17] = "Deflux",
            [18] = "Drain Soul",
            [19] = "Drain Spirit",
            [20] = "Spirit Tap",
            [21] = "Siphon Life",
            [22] = "Lifedraw",
            [23] = "Lifespike",
            [24] = "Lifetap",
        },
        ['DurationTap'] = {
            ---DurationTap >= LVL29
            [1] = "The Protector's Grasp",
            [2] = "Tserrina's Grasp",
            [3] = "Bomoda's Grasp",
            [4] = "Plexipharia's Grasp",
            [5] = "Halstor's Grasp",
            [6] = "Ivrikdal's Grasp",
            [7] = "Arachne's Grasp",
            [8] = "Fellid's Grasp",
            [9] = "Visziaj's Grasp",
            [10] = "Dyn`leth's Grasp",
            [11] = "Fang of Death",
            [12] = "Night's Beckon",
            [13] = "Saryrn's Kiss",
            [14] = "Vexing Mordinia",
            [15] = "Bond of Death",
            [16] = "Vampiric Curse",
        },
        ['GroupLeech'] = {
            ---GroupLeech >= LVL9
            [1] = "Twilight Leech",
            [2] = "Frozen Leech",
            [3] = "Ashen Leech",
            [4] = "Dark Leech",
            [5] = "Leech",
        },
        ['PoisonNuke'] = {
            ---PoisonNuke >=LVL21
            [1] = "Embalming Venin",
            [2] = "Searing Venin",
            [3] = "Effluvial Venin",
            [4] = "Liquefying Venin",
            [5] = "Dissolving Venin",
            [6] = "Blighted Venin",
            [7] = "Withering Venin",
            [8] = "Ruinous Venin",
            [9] = "Venin",
            [10] = "Acikin",
            [11] = "Neurotoxin",
            [12] = "Torbas' Venom Blast",
            [13] = "Torbas' Poison Blast",
            [14] = "Torbas' Acid Blast",
            [15] = "Shock of Poison",
        },
        ['PoisonNuke2'] = {
            ---PoisonNuke2  >=LVL 75 (DD Increase chance)
            [1] = "Proclamation for Blood",
            [2] = "Assert for Blood",
            [3] = "Refute for Blood",
            [4] = "Impose for Blood",
            [5] = "Impel for Blood",
            [6] = "Provocation for Blood",
            [7] = "Compel for Blood",
            [8] = "Exigency for Blood",
            [9] = "Supplication of Blood",
            [10] = "Demand for Blood",
        },
        ['FireDot1'] = {
            ---FireDot1 >= LVL80
            [1] = "Scalding Shadow",
            [2] = "Broiling Shadow",
            [3] = "Burning Shadow",
            [4] = "Smouldering Shadow",
            [5] = "Coruscating Shadow",
            [6] = "Blazing Shadow",
            [7] = "Blistering Shadow",
            [8] = "Scorching Shadow",
            [9] = "Searing Shadow",
        },
        ['FireDot2'] = {
            ---FireDot2 >= LVL10
            [1] = "Pyre of Va Xakra",
            [2] = "Pyre of Klraggek",
            [3] = "Pyre of the Shadewarden",
            [4] = "Pyre of Jorobb",
            [5] = "Pyre of Marnek",
            [6] = "Pyre of Hazarak",
            [7] = "Pyre of Nos",
            [8] = "Soul Reaper's Pyre",
            [9] = "Reaver's Pyre",
            [10] = "Ashengate Pyre",
            [11] = "Dread Pyre",
            [12] = "Night Fire",
            [13] = "Funeral Pyre of Kelador",
            [14] = "Pyrocruor",
            [15] = "Ignite Blood",
            [16] = "Boil Blood",
            [17] = "Heat Blood",
        },
        ['FireDot3'] = {
            ---FireDot3 >= LVL88 (QuickDOT)
            [1] = "Thall Va Kelun's Flashblaze",
            [2] = "Otatomik's Flashblaze",
            [3] = "Azeron's Flashblaze",
            [4] = "Mazub's Flashblaze",
            [5] = "Osalur's Flashblaze",
            [6] = "Brimtav's Flashblaze",
            [7] = "Tenak's Flashblaze",
        },
        ['FireDot4'] = {
            ---FireDot4 >= LVL73 DOT
            [1] = "Pyre of the Neglected",
            [2] = "Pyre of the Wretched",
            [3] = "Pyre of the Fereth",
            [4] = "Pyre of the Lost",
            [5] = "Pyre of the Forsaken",
            [6] = "Pyre of the Piq'a",
            [7] = "Pyre of the Bereft",
            [8] = "Pyre of the Forgotten",
            [9] = "Pyre of the Lifeless",
            [10] = "Pyre of the Fallen",
        },
        ['Magic1'] = {
            ---Magic1 >= LVL51 SlowDot
            [1] = "Infected Wounds",
            [2] = "Septic Wounds",
            [3] = "Cytotoxic Wounds",
            [4] = "Mortiferous Wounds",
            [5] = "Pernicious Wounds",
            [6] = "Necrotizing Wounds",
            [7] = "Splirt",
            [8] = "Splart",
            [9] = "Splort",
            [10] = "Splurt",
        },
        ['Magic2'] = {
            ---Magic2 >=LVL67 DOT
            [1] = "Extinction",
            [2] = "Oblivion",
            [3] = "Inevitable End",
            [4] = "Annihilation",
            [5] = "Termination",
            [6] = "Doom",
            [7] = "Demise",
            [8] = "Mortal Coil",
            [9] = "Anathema of Life",
            [10] = "Curse of Mortality",
            [11] = "Ancient: Curse of Mori",
            [12] = "Dark Nightmare",
            [13] = "Horror",
        },
        ['Magic3'] = {
            ---Magic3 >=LVL87 QuickDot
            [1] = "Xetheg's Swift Deconstruction",
            [2] = "Lexelan's Swift Deconstruction",
            [3] = "Adalora's Swift Deconstruction",
            [4] = "Marmat's Swift Deconstruction",
            [5] = "Itkari's Swift Deconstruction",
            [6] = "Hral's Swift Deconstruction",
            [7] = "Ninavero's Swift Deconstruction",
        },
        ['Magic4'] = {
            ---Magic4 >=LVL 97 DOT
            [1] = "Scourge of Destiny",
            [2] = "Scourge of Fates",
        },
        ['Disease1'] = {
            ---Decay Line of Disease Spells >=LVL56 Slow DOT
            [1] = "Fleshrot's Decay",
            [2] = "Danvid's Decay",
            [3] = "Mourgis' Decay",
            [4] = "Livianus' Decay",
            [5] = "Wuran's Decay",
            [6] = "Ulork's Decay",
            [7] = "Folasar's Decay",
            [8] = "Megrima's Decay",
            [9] = "Eranon's Decay",
            [10] = "Severan's Rot",
            [11] = "Chaos Plague",
            [12] = "Dark Plague",
            [13] = "Cessation of Cor",
        },
        ['Disease2'] = {
            ---Grip Line of Disease Spells =LVL1 HAS DEBUFF
            [1] = "Fleshrot's Grip of Decay",
            [2] = "Grip of Quietus",
            [3] = "Danvid's Grip of Decay",
            [4] = "Grip of Zorglim",
            [5] = "Grip of Kraz",
            [6] = "Grip of Jabaum",
            [7] = "Grip of Zalikor",
            [8] = "Grip of Zargo",
            [9] = "Grip of Mori",
            [10] = "Plague",
            [11] = "Asystole",
            [12] = "Scourge",
            [13] = "Infectious Cloud",
            [14] = "Heart Flutter",
            [15] = "Disease Cloud",
        },
        ['Disease3'] = {
            ---Sickness Life of Disease Spells >=LVL89 QuickDOT
            [1] = "Diabo Tatrua's Swift Sickness",
            [2] = "Lairsaf's Swift Sickness",
            [3] = "Hoshkar's Swift Sickness",
            [4] = "Ilsaria's Swift Sickness",
            [5] = "Bora's Swift Sickness",
            [6] = "Prox's Swift Sickness",
            [7] = "Rilfed's Swift Sickness",
        },
        ['Poison1'] = {
            ---Poison1 >= LVL86 (QuickDOT)
            [1] = "Xenacious' Swift Venom",
            [2] = "Vilefang's Swift Venom",
            [3] = "Nexona's Swift Venom",
            [4] = "Serisaria's Swift Venom",
            [5] = "Slaunk's Swift Venom",
            [6] = "Hyboram's Swift Venom",
            [7] = "Burlabis' Swift Venom",
        },
        ['Poison2'] = {
            ---Poison2 >=LVL1 (DOT)
            [1] = "Hemorrhagic Venom",
            [2] = "Crystal Crawler Venom",
            [3] = "Polybiad Venom",
            [4] = "Glistenwing Venom",
            [5] = "Binaesa Venom",
            [6] = "Naeya Venom",
            [7] = "Argendev's Venom",
            [8] = "Slitheren Venom",
            [9] = "Venonscale Venom",
            [10] = "Vakk`dra's Sickly Mists",
            [11] = "Blood of Thule",
            [12] = "Envenomed Bolt",
            [13] = "Chilling Embrace",
            [14] = "Venom of the Snake",
            [15] = "Poison Bolt",
        },
        ['Poison3'] = {
            ---Poison3 >= LVL79 DOT
            [1] = "Zelnithak's Pallid Haze",
            [2] = "Dracnia's Pallid Haze",
            [3] = "Bomoda's Pallid Haze",
            [4] = "Plexipharia's Pallid Haze",
            [5] = "Halstor's Pallid Haze",
            [6] = "Ivrikdal's Pallid Haze",
            [7] = "Arachne's Pallid Haze",
            [8] = "Fellid's Pallid Haze",
            [9] = "Visziaj's Pallid Haze",
            [10] = "Chaos Venom",
        },
        ['Corruption1'] = {
            ---Corruption1 >= LVL77
            [1] = "Decomposition",
            [2] = "Miasma",
            [3] = "Effluvium",
            [4] = "Liquefaction",
            [5] = "Dissolution",
            [6] = "Mortification",
            [7] = "Fetidity",
            [8] = "Putrescence",
            [9] = "Putrefaction",
        },
        ['CripplingTap'] = {
            -- >= LVL56 Crippling Claudication
            [1] = "Crippling Paraplegia",
            [2] = "Crippling Incapacity",
            [3] = "Crippling Claudication",
        },
        ['ChaoticDebuff'] = {
            -- >= LVL93
            -- Chaotic Contgion
            [1] = "Chaotic Acridness",
            [2] = "Chaotic Miasma",
            [3] = "Chaotic Effluvium",
            [4] = "Chaotic Liquefaction",
            [5] = "Chaotic Corruption",
            [6] = "Chaotic Contagion",
        },
        ['SnareDOT'] = {
            -- LVL4 -> <= LVL70
            [1] = "Harrowing Darkness",
            [2] = "Tormenting Darkness",
            [3] = "Gnawing Darkness",
            [4] = "Grasping Darkness",
            [5] = "Clutching Darkness",
            [6] = "Viscous Darkness",
            [7] = "Tenuous Darkness",
            [8] = "Clawing Darkness",
            [9] = "Auroral Darkness",
            [10] = "Coruscating Darkness",
            [11] = "Desecrating Darkness",
            [12] = "Embracing Darkness",
            [13] = "Devouring Darkness",
            [14] = "Cascading Darkness",
            [15] = "Scent of Darkness",
            [16] = "Dooming Darkness",
            [17] = "Engulfing Darkness",
            [18] = "Clinging Darkness",
        },
        ['ScentDebuff'] = {
            -- line needed till >= LVL10 <= LVL85
            [1] = "Scent of The Grave",
            [2] = "Scent of Mortality",
            [3] = "Scent of Extinction",
            [4] = "Scent of Dread",
            [5] = "Scent of Nightfall",
            [6] = "Scent of Doom",
            [7] = "Scent of Gloom",
            [8] = "Scent of Afterlight",
            [9] = "Scent of Twilight",
            [10] = "Scent of Midnight",
            [11] = "Scent of Terris",
            [12] = "Scent of Darkness",
            [13] = "Scent of Shadow",
            [14] = "Scent of Dusk",
        },
        ['LichSpell'] = {
            -- LichForm Spell
            [1] = "Lunaside",
            [2] = "Gloomside",
            [3] = "Contraside",
            [4] = "Forgottenside",
            [5] = "Forsakenside",
            [6] = "Shadowside",
            [7] = "Darkside",
            [8] = "Netherside",
            [9] = "Spectralside",
            [10] = "Otherside",
            [11] = "Dark Possession",
            [12] = "Grave Pact",
            [13] = "Seduction of Saryrn",
            [14] = "Arch Lich",
            [15] = "Demi Lich",
            [16] = "Lich",
            [17] = "Call of Bones",
            [18] = "Allure of Death",
            [19] = "Dark Pact",
        },
        ['BestowBuff'] = {
            -- Bestow Line
            [1] = "Bestow Rot",
            [2] = "Bestow Dread",
            [3] = "Bestow Relife",
            [4] = "Bestow Doom",
            [5] = "Bestow Mortality",
            [6] = "Bestow Decay",
            [7] = "Bestow Unlife",
            [8] = "Bestow Undeath",
        },
        ['PetSpellRog'] = {
            ---Pet Spells Rogue * Var Name:, string outer
            [1] = "Unrelenting Assassin",
            [2] = "Restless Assassin",
            [3] = "Reliving Assassin",
            [4] = "Restless Assassin",
            [5] = "Unearthed Assassin",
            [6] = "Reborn Assassin",
            [7] = "Raised Assassin",
            [8] = "Unliving Murderer",
            [9] = "Noxious Servant",
            [10] = "Putrescent Servant",
            [11] = "Dark Assassin",
            [12] = "Child of Bertoxxulous",
            [13] = "Saryrn's Companion",
            [14] = "Minion of Shadows",
        },
        ['PetSpellWar'] = {
            ---Pet Spells Warrior
            [1] = "Luclin's Conqueror",
            [2] = "Tserrina's Shade",
            [3] = "Adalora's Shade",
            [4] = "Miktokla's Shade",
            [5] = "Zalifur's Shade",
            [6] = "Vak`Ridel's Shade",
            [7] = "Aziad's Shade",
            [8] = "Bloodreaper's Shade",
            [9] = "Relamar's Shade",
            [10] = "Riza`farr's Shadow",
            [11] = "Lost Soul",
            [12] = "Emissary of Thule",
            [13] = "Servant of Bones",
            [14] = "Invoke Death",
            [15] = "Cackling Bones",
            [16] = "Malignant Dead",
            [17] = "Invoke Shadow",
            [18] = "Summon Dead",
            [19] = "Haunting Corpse",
            [20] = "Animate Dead",
            [21] = "Restless Bones",
            [22] = "Convoke Shadow",
            [23] = "Bone Walk",
            [24] = "Leering Corpse",
            [25] = "Cavorting Bones",
        },
        ['PetBuff'] = {
            ---Pet Buff Spell * Var Name:, string outer
            [1] = "Inspire Ally",
            [2] = "Incite Ally",
            [3] = "Infuse Ally",
            [4] = "Imbue Ally",
            [5] = "Sanction Ally",
            [6] = "Empower Ally",
            [7] = "Energize Ally",
            [8] = "Necrotize Ally",
        },
        ['PetHaste'] = {
            ---Pet Haste Spell * Var Name:, string outer
            [1] = "Sigil of Undeath",
            [2] = "Sigil of Decay",
            [3] = "Sigil of the Arcron",
            [4] = "Sigil of the Doomscale",
            [5] = "Sigil of the Sundered",
            [6] = "Sigil of the Preternatural",
            [7] = "Sigil of the Moribund",
            [8] = "Sigil of the Aberrant",
            [9] = "Sigil of the Unnatural",
            [10] = "Glyph of Darkness",
            [11] = "Rune of Death",
            [12] = "Augmentation of Death",
            [13] = "Augment Death",
            [14] = "Intensify Death",
            [15] = "Focus Death",
        },
    },
    ['Rotations'] = {
        ['Tank'] = {
            ['Rotation'] = {
                ['Burn'] = {
                    [1] = {},
                },
                ['Debuff'] = {
                    [1] = {},
                },
                ['Heal'] = {
                    [1] = {},
                },
                ['DPS'] = {
                    [1] = {},
                },
                ['Downtime'] = {
                    [1] = {},
                },
            },
            ['Spells'] = {
                [1] = { name = "", gem = 1 },
                [2] = { name = "", gem = 2 },
                [3] = { name = "", gem = 3 },
                [4] = { name = "", gem = 4 },
                [5] = { name = "", gem = 5 },
                [6] = { name = "", gem = 6 },
                [7] = { name = "", gem = 7 },
                [8] = { name = "", gem = 8 },
                [9] = { name = "", gem = 9 },
                [10] = { name = "", gem = 10 },
                [11] = { name = "", gem = 11 },
                [12] = { name = "", gem = 12 },
            },
        },
        ['DPS'] = {
            ['Rotation'] = {
                ['Burn'] = {
                    [1] = {},
                },
                ['Debuff'] = {
                    [1] = {},
                },
                ['Heal'] = {
                    [1] = {},
                },
                ['DPS'] = {
                    [1] = {},
                },
                ['Downtime'] = {
                    [1] = {},
                },
            },
            ['Spells'] = {
                [1] = { name = "", gem = 1 },
                [2] = { name = "", gem = 2 },
                [3] = { name = "", gem = 3 },
                [4] = { name = "", gem = 4 },
                [5] = { name = "", gem = 5 },
                [6] = { name = "", gem = 6 },
                [7] = { name = "", gem = 7 },
                [8] = { name = "", gem = 8 },
                [9] = { name = "", gem = 9 },
                [10] = { name = "", gem = 10 },
                [11] = { name = "", gem = 11 },
                [12] = { name = "", gem = 12 },
            },
        },
        ['Healer'] = {
            ['Rotation'] = {
                ['Burn'] = {
                    [1] = {},
                },
                ['Debuff'] = {
                    [1] = {},
                },
                ['Heal'] = {
                    [1] = {},
                },
                ['DPS'] = {
                    [1] = {},
                },
                ['Downtime'] = {
                    [1] = {},
                },
            },
            ['Spells'] = {
                [1] = { name = "", gem = 1 },
                [2] = { name = "", gem = 2 },
                [3] = { name = "", gem = 3 },
                [4] = { name = "", gem = 4 },
                [5] = { name = "", gem = 5 },
                [6] = { name = "", gem = 6 },
                [7] = { name = "", gem = 7 },
                [8] = { name = "", gem = 8 },
                [9] = { name = "", gem = 9 },
                [10] = { name = "", gem = 10 },
                [11] = { name = "", gem = 11 },
                [12] = { name = "", gem = 12 },
            },
        },
        ['Hybrid'] = {
            ['Rotation'] = {
                ['Burn'] = {
                    [1] = {},
                },
                ['Debuff'] = {
                    [1] = {},
                },
                ['Heal'] = {
                    [1] = {},
                },
                ['DPS'] = {
                    [1] = {},
                },
                ['Downtime'] = {
                    [1] = {},
                },
            },
            ['Spells'] = {
                [1] = { name = "", gem = 1 },
                [2] = { name = "", gem = 2 },
                [3] = { name = "", gem = 3 },
                [4] = { name = "", gem = 4 },
                [5] = { name = "", gem = 5 },
                [6] = { name = "", gem = 6 },
                [7] = { name = "", gem = 7 },
                [8] = { name = "", gem = 8 },
                [9] = { name = "", gem = 9 },
                [10] = { name = "", gem = 10 },
                [11] = { name = "", gem = 11 },
                [12] = { name = "", gem = 12 },
            },
        },
        ['DefaultConfig'] = {
            ['Mode'] = '1',
        },
    },
}
