local mq          = require('mq')
local RGMercUtils = require("utils.rgmercs_utils")

return {
    ['CommandHandlers'] = {
        makeammo = function(self, ...)
            RGMercsLogger.log_info("I would make ammo, if I only knew how.")
            return true
        end,
    },
    ['Modes'] = {
        'Tank',
        'DPS',
        'Healer',
        'Hybrid',
    },
    ['ItemSets'] = {
        ['Epic'] = {
            "Heartwood Blade",
            "Aurora, the Heartwood Blade",
        },
    },
    ['AbilitySets'] = {
        ["ArrowOpener"] = {
            "Silent Shot",
            "Stealthy Shot",
        },
        ["PullOpener"] = {
            "Deadfall",
            "Heartpierce",
            "Heartrend",
            "Heartrip",
            "Heartspike",
        },
        ["CalledShotsArrow"] = {
            "Called Shots",
            "Announced Shots",
            "Forecasted Shots",
            "Anticipated Shots",
            "Foreseen Shots",
            "Marked Shots",
            "Claimed Shots",
            "Inevitable Shots",
        },
        ["FocusedArrows"] = {
            "Focused Frenzy of Arrows",
            "Focused Storm of Arrows",
            "Focused Tempest of Arrows",
            "Focused Arrow Swarm",
            "Focused Rain of Arrows",
            "Focused Arrowrain",
            "Focused Arrowgale",
            "Focused Blizzard of Arrows",
            "Focused Whirlwind of Arrows",
        },
        ["DichoSpell"] = {
            "Dichotomic Fusillade",
            "Dissident Fusillade",
            "Composite Fusillade",
            "Ecliptic Fusillade",
        },
        ["SummerNuke"] = {
            "Summer's Deluge",
            "Summer's Torrent",
            "Summer's Viridity",
            "Summer's Mist",
            "Summer's Storm",
            "Summer's Squall",
            "Summer's Gale",
            "Summer's Cyclone",
            "Summer's Tempest",
            "Summer's Sleet",
        },
        ["SwarmDot"] = {
            "Stinging Swarm",
            "Swarm of Pain",
            "Drones of Doom",
            "Fire Swarm",
            "Drifting Death",
            "Locust Swarm",
            "Wasp Swarm",
            "Hornet Swarm",
            "Beetle Swarm",
            "Scarab Swarm",
            "Vespid Swarm",
            "Dreadbeetle Swarm",
            "Blisterbeetle Swarm",
            "Bonecrawler Swarm",
            "Ice Burrower Swarm",
            "Bloodbeetle Swarm",
            "Hotaria Swarm",
        },
        ["ShortSwarmDot"] = {
            "Swarm of Fernflies",
            "Swarm of Bloodflies",
            "Swarm of Hyperboreads",
            "Swarm of Glistenwings",
            "Swarm of Vespines",
            "Swarm of Sand Wasps",
            "Swarm of Hornets",
            "Swarm of Bees",
        },
        ["UnityBuff"] = {
            "Bosquetender's Unity",
            "Copsestalker's Unity",
            "Wildstalker's Unity",
        },
        ["Protectionbuff"] = {
            "Riftwind's Protection",
            "Force of Nature",
            "Warder's Protection",
            "Protection of the Wild",
            "Protection of the Minohten",
            "Protection of the Kirkoten",
            "Protection of the Paw",
            "Protection of the Vale",
            "Protection of the Copse",
            "Protection of the Bosque",
            "Protection of the Forest",
            "Protection of the Woodlands",
            "Protection of the Wakening Land",
            "Protection of the Valley",
        },
        ["ShoutBuff"] = {
            "Shout of the Predator",
            "Shout of the Bosquestalker",
            "Shout of the Copsestalker",
            "Shout of the Wildstalker",
            "Shout of the Arbor Stalker",
            "Shout of the Dusksage Stalker",
        },
        ["AgroBuff"] = {
            "Devastating Blades",
            "Devastating Edges",
            "Devastating Slashes",
            "Devastating Impact",
            "Devastating Swords",
            "Devastating Steel",
            "Devastating Velium",
            "Devastating Barrage",
        },
        ["AgroReducerBuff"] = {
            "Jolting Blades",
            "Jolting Strikes",
            "Jolting Swings",
            "Jolting Edges",
            "Jolting Impact",
            "Jolting Shock",
            "Jolting Swords",
            "Jolting Steel",
            "Jolting Velium",
            "Jolting Luclinite",
        },
        ["AggroKick"] = {
            "Enraging Roundhouse Kicks",
            "Enraging Axe Kicks",
            "Enraging Wheel Kicks",
            "Enraging Cut Kicks",
            "Enraging Heel Kicks",
            "Enraging Crescent Kicks",
        },
        ["ParryProcBuff"] = {
            "Crackling Blades",
            "Crackling Edges",
            "Deafening Edges",
            "Deafening Weapons",
            "Roaring Weapons",
            "Roaring Blades",
            "Howling Blades",
            "Vociferous Blades",
        },
        ["RunSpeedBuff"] = {
            "Spirit of Eagle",
            "Spirit of Falcons",
        },
        ["Eyes"] = {
            "Hawk Eye",
            "Falcon Eye",
            "Eagle Eye",
            "Eyes of the Owl",
            "Eyes of the Peregrine",
            "Eyes of the Nocturnal",
            "Eyes of the Wolf",
            "Eyes of the Raptor",
            "Eyes of the Howler",
            "Eyes of the Harrier",
            "Eyes of the Sabertooth",
            "Eyes of the Visionary",
            "Eyes of the Senshali",
            "Eyes of the Phoenix",
        },
        ["GroupStrengthBuff"] = {
            "Nature's Precision",
            "Strength of Nature",
            "Strength of Tunare",
            "Strength of the Hunter",
            "Strength of the Forest Stalker",
            "Strength of the Gladewalker",
            "Strength of the Tracker",
            "Strength of the Thicket Stalker",
            "Strength of the Gladetender",
            "Strength of the Bosquestalker",
            "Strength of the Copsestalker",
            "Strength of the Wildstalker",
            "Strength of the Arbor Stalker",
            "Shout of the Dusksage Stalker",
            "Shout of the Fernstalker",
        },
        ["GroupPredatorBuff"] = {
            "Mark of the Predator",
            "Call of the Predator",
            "Spirit of the Predator",
            "Howl of the Predator",
            "Snarl of the Predator",
            "Gnarl of the Predator",
            "Yowl of the Predator",
            "Roar of the Predator",
            "Cry of the Predator",
            "Shout of the Predator",
            "Shout of the Bosquestalker",
            "Bellow of the Predator",
            "Wail of the Predator",
            "Frostroar of the Predator",
            "Shout of the Dusksage Stalker",
            "Shout of the Fernstalker",
        },
        ["GroupEnrichmentBuff"] = {
            "Arbor Stalker's Enrichment",
            "Copsestalker's Enrichment",
            "Wildstalker's Enrichment",
        },
        ["Rathe"] = {
            "Cloak of Needlespikes",
            "Cloak of Bloodbarbs",
            "Shared, of Rimespurs",
            "Cloak of Rimespurs",
            "Shared, of Needlebarbs",
            "Cloak of Needlebarbs",
            "Cloak of Nettlespears",
            "Shared, of Spurs",
            "Cloak of Spurs",
            "Shared, of Burrs",
            "Cloak of Burrs",
            "Cloak of Quills",
            "Cloak of Feathers",
            "Cloak of Scales",
            "Call of the,",
            "Guard of the Earth",
            "Riftwind's Protection",
        },
        ["BowDisc"] = {
            "Trueshot Discipline",
            "Aimshot Discipline",
            "Sureshot Discipline",
            "Pureshot Discipline",
        },
        ["MeleeDisc"] = {
            "Fernstalker's Discipline",
            "Dusksage Stalker's Discipline",
            "Bosquestalker's Discipline",
            "Copsestalker's Discipline",
            "Wildstalker's Discipline",
            "Arbor Stalker's Discipline",
        },
        ["DefenseDisc"] = {
            "Weapon Shield Discipline",
        },
        ["Fireboon"] = {
            "Ashcloud Boon",
            "Wildfire Boon",
            "Skyfire Boon",
            "Pyroclastic Boon",
            "Lunarflare Boon",
        },
        ["Firenuke"] = {
            "Flame Lick",
            "Burst of Fire",
            "Ignite",
            "Flaming Arrow",
            "Burning Arrow",
            "Call of Flame",
            "FireStrike",
            "Brushfire",
            "Sylvan Burn",
            "Ancient: Burning Chaos",
            "Hearth Embers",
            "Scorched Earth",
            "Volcanic Ash",
            "Galvanic Ash",
            "Cataclysm Ash",
            "Burning Ash",
            "Beastwood Ash",
            "Vileoak Ash",
            "Wildfire Ash",
            "Skyfire Ash",
            "Pyroclastic Ash",
            "Lunarflare Ash",
        },
        ["Iceboon"] = {
            "Mistral Boon",
            "Windblast Boon",
            "Windgale Boon",
            "Windshear Boon",
            "Nocturnal Boon",
        },
        ["Icenuke"] = {
            "Bitter Wind",
            "Frozen Wind",
            "Frigid Wind",
            "Restless Wind",
            "Coagulated Wind",
        },
        ["Heartshot"] = {
            "Heartshot",
            "Heartsting",
            "Heartsting",
            "Heartslice",
            "Heartslash",
            "Heartsplit",
            "Heartcleave",
            "Heartsunder",
            "Heartruin",
        },
        ["EndRegenDisc"] = {
            "Second Wind",
            "Third Wind",
            "Fourth Wind",
            "Respite",
            "Reprieve",
            "Rest",
            "Breather",
            "Hiatus",
            "Relax",
            "Night's Calming",
            "Convalesce",
        },
        ["Coat"] = {
            "ThistleCoat",
            "Barbcoat",
            "Bramblecoat",
            "Spikecoat",
            "Thorncoat",
            "Bladecoat",
            "Briarcoat",
            "Spinecoat",
            "Quillcoat",
            "Burrcoat",
            "Spurcoat",
            "Nettlespear,",
            "Needlebarb,",
            "Rimespur,",
            "Moonthorn,",
            "Needlespike,",
        },
        ["Mask"] = {
            "Mask of the Stalker",
        },
        ["hunt"] = {
            "Engulfed by the Hunt",
            "Consumed by the Hunt",
            "Invigorated by the Hunt",
            "Galvanized by the Hunt",
            "Inspired by the Hunt",
            "Energized by the Hunt",
            "Spurred by the Hunt",
            "Provoked by the Hunt",
            "Steeled by the Hunt",
        },
        ["Heal"] = {
            "Elizerain Spring",
            "Darkflow Spring",
            "Meltwater Spring",
            "Wellspring",
            "Cloudfont",
            "Cloudburst",
            "Purespring",
            "Purefont",
            "Oceangreen Aquifer",
            "Dragonscale Aquifer",
            "Sunderock Springwater",
            "Sylvan Water",
            "Sylvan Light",
            "Chloroblast",
            "Greater Healing",
            "Light Healing",
            "Healing",
            "Minor Healing",
            "Salve",
        },
        ["Fastheal"] = {
            "Desperate Quenching",
            "Desperate Geyser",
            "Desperate Deluge",
            "Desperate Downpour",
            "Desperate Drenching",
            "Desperate Dousing",
            "Desperate Dewcloud",
            "Desperate Meltwater",
        },
        ["Totheal"] = {
            "Desperate Quenching",
            "Desperate Geyser",
            "Darkflow Spring",
            "Desperate Meltwater",
            "Meltwater Spring",
        },
        ["SnareSpells"] = {
            "Snare",
            "Tangling Weeds",
            "Ensnare",
            "Earthen Embrace",
            "Earthen Shackles",
        },
        ["FireFist"] = {
            "Firefist",
            "Nature's Precision",
            "Wolf Form",
            "Greater Wolf Form",
            "Feral Form",
        },
        ["DsBuff"] = {
            "Shield of Thistles",
            "Shield of Brambles",
            "Shield of Spikes",
            "Shield of Thorns",
            "Shield of Briar",
            "Shield of Needles",
            "Shield of Spurs",
            "Shield of DrySpines",
            "Shield of Nettlespikes",
            "Shield of Bramblespikes",
            "Shield of Nettlespines",
            "Shield of Nettlespears",
            "Shield of Needlebarbs",
            "Shield of Rimespurs",
            "Shield of Shadethorns",
        },
        ["SkinLike"] = {
            "Skin Like Wood",
            "Skin Like Rock",
            "Skin Like Steel",
            "Skin Like Diamond",
            "Skin Like Nature",
        },
        ["MoveSpells"] = {
            "Spirit of Falcons",
            "Spirit of Eagle",
            "Pack Shrew",
            "Spirit of the Shrew",
            "Spirit of Wolf",
        },
        ["Alliance"] = {
            "Bosquestalker's",
            "Wildstalker's Covenant",
            "Arbor Stalker's Coalition",
            "Dusksage Stalker's Conjunction",
        },
        ["AgiBuff"] = {
            "Feet Like Cat",
        },
        ["Cloak"] = {
            "Shalowain's Crucible,",
            "Luclin's Darkfire,",
            "Outrider's Ever-Burning,",
            "Lavastorm,",
            "Ro's Burning,",
        },
        ["Veil"] = {
            "Shadowveil",
            "Duskveil",
            "Frostveil",
            "Vaporous,",
            "Shimmering,",
            "Arbor,",
            "Veil of Alaris",
            "Nature,",
        },
        ["JoltingKicks"] = {
            "Jolting Frontkicks",
            "Jolting Hook Kicks",
            "Jolting Crescent Kicks",
            "Jolting Heel Kicks",
            "Jolting Cut Kicks",
            "Jolting Wheel Kicks",
            "Jolting Axe Kicks",
            "Jolting Roundhouse Kicks",
            "Jolting Drop Kicks",
        },
        ["AEBlades"] = {
            "Storm of Blades",
            "Squall Of Blades",
            "Gale of Blades",
            "Blizzard of Blades",
            "Tempest of Blades",
            "Maelstrom of Blades",
        },
        ["FocusedBlades"] = {
            "Focused Storm of Blades",
            "Focused Squall of Blades",
            "Focused Gale of Blades",
            "Focused Blizzard of Blades",
            "Focused Tempest of Blades",
        },
        ["ReflexSlashHeal"] = {
            "Reflexive Bladespurs",
            "Reflexive Nettlespears",
            "Reflexive Rimespurs",
        },
    },
    ['Rotations'] = {
        ['Tank'] = {
            ['Rotation'] = {
                ['Burn'] = {
                    {},
                },
                ['Debuff'] = {
                    {},
                },
                ['Heal'] = {
                    {},
                },
                ['DPS'] = {
                    {},
                },
                ['Downtime'] = {
                    {},
                },
            },
            ['Spells'] = {
                { name = "", gem = 1, },
                { name = "", gem = 2, },
                { name = "", gem = 3, },
                { name = "", gem = 4, },
                { name = "", gem = 5, },
                { name = "", gem = 6, },
                { name = "", gem = 7, },
                { name = "", gem = 8, },
                { name = "", gem = 9, },
                { name = "", gem = 10, },
                { name = "", gem = 11, },
                { name = "", gem = 12, },
            },
        },
        ['DPS'] = {
            ['Rotation'] = {
                ['Burn'] = {
                    {},
                },
                ['Debuff'] = {
                    {},
                },
                ['Heal'] = {
                    {},
                },
                ['DPS'] = {
                    {},
                },
                ['Downtime'] = {
                    {},
                },
            },
            ['Spells'] = {
                { name = "", gem = 1, },
                { name = "", gem = 2, },
                { name = "", gem = 3, },
                { name = "", gem = 4, },
                { name = "", gem = 5, },
                { name = "", gem = 6, },
                { name = "", gem = 7, },
                { name = "", gem = 8, },
                { name = "", gem = 9, },
                { name = "", gem = 10, },
                { name = "", gem = 11, },
                { name = "", gem = 12, },
            },
        },
        ['Healer'] = {
            ['Rotation'] = {
                ['Burn'] = {
                    {},
                },
                ['Debuff'] = {
                    {},
                },
                ['Heal'] = {
                    {},
                },
                ['DPS'] = {
                    {},
                },
                ['Downtime'] = {
                    {},
                },
            },
            ['Spells'] = {
                { name = "", gem = 1, },
                { name = "", gem = 2, },
                { name = "", gem = 3, },
                { name = "", gem = 4, },
                { name = "", gem = 5, },
                { name = "", gem = 6, },
                { name = "", gem = 7, },
                { name = "", gem = 8, },
                { name = "", gem = 9, },
                { name = "", gem = 10, },
                { name = "", gem = 11, },
                { name = "", gem = 12, },
            },
        },
        ['Hybrid'] = {
            ['Rotation'] = {
                ['Burn'] = {
                    {},
                },
                ['Debuff'] = {
                    {},
                },
                ['Heal'] = {
                    {},
                },
                ['DPS'] = {
                    {},
                },
                ['Downtime'] = {
                    {},
                },
            },
            ['Spells'] = {
                { name = "", gem = 1, },
                { name = "", gem = 2, },
                { name = "", gem = 3, },
                { name = "", gem = 4, },
                { name = "", gem = 5, },
                { name = "", gem = 6, },
                { name = "", gem = 7, },
                { name = "", gem = 8, },
                { name = "", gem = 9, },
                { name = "", gem = 10, },
                { name = "", gem = 11, },
                { name = "", gem = 12, },
            },
        },
        ['DefaultConfig'] = {
            ['Mode'] = '1',
        },
    },
}
