return {
    ['Modes'] = {
        ['DPS'] = 0,
        ['TLP'] = 1,
        ['Tank'] = 2,
    },
    ['ItemSets'] = {
        ['Epic'] = {
            [1] = "Heartwood Blade",
            [2] = "Aurora, the Heartwood Blade",
        },
    },
    ['AbilitySets'] = {
        ["ArrowOpener"] = {
            [1] = "Silent Shot",
            [2] = "Stealthy Shot",
        },
        ["PullOpener"] = {
            [1] = "Deadfall",
            [2] = "Heartpierce",
            [3] = "Heartrend",
            [4] = "Heartrip",
            [5] = "Heartspike",
        },
        ["CalledShotsArrow"] = {
            [1] = "Called Shots",
            [2] = "Announced Shots",
            [3] = "Forecasted Shots",
            [4] = "Anticipated Shots",
            [5] = "Foreseen Shots",
            [6] = "Marked Shots",
            [7] = "Claimed Shots",
            [8] = "Inevitable Shots",
        },
        ["FocusedArrows"] = {
            [1] = "Focused Frenzy of Arrows",
            [2] = "Focused Storm of Arrows",
            [3] = "Focused Tempest of Arrows",
            [4] = "Focused Arrow Swarm",
            [5] = "Focused Rain of Arrows",
            [6] = "Focused Arrowrain",
            [7] = "Focused Arrowgale",
            [8] = "Focused Blizzard of Arrows",
            [9] = "Focused Whirlwind of Arrows",
        },
        ["DichoSpell"] = {
            [1] = "Dichotomic Fusillade",
            [2] = "Dissident Fusillade",
            [3] = "Composite Fusillade",
            [4] = "Ecliptic Fusillade",
        },
        ["SummerNuke"] = {
            [1] = "Summer's Deluge",
            [2] = "Summer's Torrent",
            [3] = "Summer's Viridity",
            [4] = "Summer's Mist",
            [5] = "Summer's Storm",
            [6] = "Summer's Squall",
            [7] = "Summer's Gale",
            [8] = "Summer's Cyclone",
            [9] = "Summer's Tempest",
            [10] = "Summer's Sleet",
        },
        ["SwarmDot"] = {
            [1] = "Stinging Swarm",
            [2] = "Swarm of Pain",
            [3] = "Drones of Doom",
            [4] = "Fire Swarm",
            [5] = "Drifting Death",
            [6] = "Locust Swarm",
            [7] = "Wasp Swarm",
            [8] = "Hornet Swarm",
            [9] = "Beetle Swarm",
            [10] = "Scarab Swarm",
            [11] = "Vespid Swarm",
            [12] = "Dreadbeetle Swarm",
            [13] = "Blisterbeetle Swarm",
            [14] = "Bonecrawler Swarm",
            [15] = "Ice Burrower Swarm",
            [16] = "Bloodbeetle Swarm",
            [17] = "Hotaria Swarm",
        },
        ["ShortSwarmDot"] = {
            [1] = "Swarm of Fernflies",
            [2] = "Swarm of Bloodflies",
            [3] = "Swarm of Hyperboreads",
            [4] = "Swarm of Glistenwings",
            [5] = "Swarm of Vespines",
            [6] = "Swarm of Sand Wasps",
            [7] = "Swarm of Hornets",
            [8] = "Swarm of Bees",
        },
        ["UnityBuff"] = {
            [1] = "Bosquetender's Unity",
            [2] = "Copsestalker's Unity",
            [3] = "Wildstalker's Unity",
        },
        ["Protectionbuff"] = {
            [1] = "Riftwind's Protection",
            [2] = "Force of Nature",
            [3] = "Warder's Protection",
            [4] = "Protection of the Wild",
            [5] = "Protection of the Minohten",
            [6] = "Protection of the Kirkoten",
            [7] = "Protection of the Paw",
            [8] = "Protection of the Vale",
            [9] = "Protection of the Copse",
            [10] = "Protection of the Bosque",
            [11] = "Protection of the Forest",
            [12] = "Protection of the Woodlands",
            [13] = "Protection of the Wakening Land",
            [14] = "Protection of the Valley",
        },
        ["ShoutBuff"] = {
            [1] = "Shout of the Predator",
            [2] = "Shout of the Bosquestalker",
            [3] = "Shout of the Copsestalker",
            [4] = "Shout of the Wildstalker",
            [5] = "Shout of the Arbor Stalker",
            [6] = "Shout of the Dusksage Stalker",
        },
        ["AgroBuff"] = {
            [1] = "Devastating Blades",
            [2] = "Devastating Edges",
            [3] = "Devastating Slashes",
            [4] = "Devastating Impact",
            [5] = "Devastating Swords",
            [6] = "Devastating Steel",
            [7] = "Devastating Velium",
            [8] = "Devastating Barrage",
        },
        ["AgroReducerBuff"] = {
            [1] = "Jolting Blades",
            [2] = "Jolting Strikes",
            [3] = "Jolting Swings",
            [4] = "Jolting Edges",
            [5] = "Jolting Impact",
            [6] = "Jolting Shock",
            [7] = "Jolting Swords",
            [8] = "Jolting Steel",
            [9] = "Jolting Velium",
            [10] = "Jolting Luclinite",
        },
        ["AggroKick"] = {
            [1] = "Enraging Roundhouse Kicks",
            [2] = "Enraging Axe Kicks",
            [3] = "Enraging Wheel Kicks",
            [4] = "Enraging Cut Kicks",
            [5] = "Enraging Heel Kicks",
            [6] = "Enraging Crescent Kicks",
        },
        ["ParryProcBuff"] = {
            [1] = "Crackling Blades",
            [2] = "Crackling Edges",
            [3] = "Deafening Edges",
            [4] = "Deafening Weapons",
            [5] = "Roaring Weapons",
            [6] = "Roaring Blades",
            [7] = "Howling Blades",
            [8] = "Vociferous Blades",
        },
        ["RunSpeedBuff"] = {
            [1] = "Spirit of Eagle",
            [2] = "Spirit of Falcons",
        },
        ["Eyes"] = {
            [1] = "Hawk Eye",
            [2] = "Falcon Eye",
            [3] = "Eagle Eye",
            [4] = "Eyes of the Owl",
            [5] = "Eyes of the Peregrine",
            [6] = "Eyes of the Nocturnal",
            [7] = "Eyes of the Wolf",
            [8] = "Eyes of the Raptor",
            [9] = "Eyes of the Howler",
            [10] = "Eyes of the Harrier",
            [11] = "Eyes of the Sabertooth",
            [12] = "Eyes of the Visionary",
            [13] = "Eyes of the Senshali",
            [14] = "Eyes of the Phoenix",
        },
        ["GroupStrengthBuff"] = {
            [1] = "Nature's Precision",
            [2] = "Strength of Nature",
            [3] = "Strength of Tunare",
            [4] = "Strength of the Hunter",
            [5] = "Strength of the Forest Stalker",
            [6] = "Strength of the Gladewalker",
            [7] = "Strength of the Tracker",
            [8] = "Strength of the Thicket Stalker",
            [9] = "Strength of the Gladetender",
            [10] = "Strength of the Bosquestalker",
            [11] = "Strength of the Copsestalker",
            [12] = "Strength of the Wildstalker",
            [13] = "Strength of the Arbor Stalker",
            [14] = "Shout of the Dusksage Stalker",
            [15] = "Shout of the Fernstalker",
        },
        ["GroupPredatorBuff"] = {
            [1] = "Mark of the Predator",
            [2] = "Call of the Predator",
            [3] = "Spirit of the Predator",
            [4] = "Howl of the Predator",
            [5] = "Snarl of the Predator",
            [6] = "Gnarl of the Predator",
            [7] = "Yowl of the Predator",
            [8] = "Roar of the Predator",
            [9] = "Cry of the Predator",
            [10] = "Shout of the Predator",
            [11] = "Shout of the Bosquestalker",
            [12] = "Bellow of the Predator",
            [13] = "Wail of the Predator",
            [14] = "Frostroar of the Predator",
            [15] = "Shout of the Dusksage Stalker",
            [16] = "Shout of the Fernstalker",
        },
        ["GroupEnrichmentBuff"] = {
            [1] = "Arbor Stalker's Enrichment",
            [2] = "Copsestalker's Enrichment",
            [3] = "Wildstalker's Enrichment",
        },
        ["Rathe"] = {
            [1] = "Cloak of Needlespikes",
            [2] = "Cloak of Bloodbarbs",
            [3] = "Shared, of Rimespurs",
            [4] = "Cloak of Rimespurs",
            [5] = "Shared, of Needlebarbs",
            [6] = "Cloak of Needlebarbs",
            [7] = "Cloak of Nettlespears",
            [8] = "Shared, of Spurs",
            [9] = "Cloak of Spurs",
            [10] = "Shared, of Burrs",
            [11] = "Cloak of Burrs",
            [12] = "Cloak of Quills",
            [13] = "Cloak of Feathers",
            [14] = "Cloak of Scales",
            [15] = "Call of the,",
            [16] = "Guard of the Earth",
            [17] = "Riftwind's Protection",
        },
        ["BowDisc"] = {
            [1] = "Trueshot Discipline",
            [2] = "Aimshot Discipline",
            [3] = "Sureshot Discipline",
            [4] = "Pureshot Discipline",
        },
        ["MeleeDisc"] = {
            [1] = "Fernstalker's Discipline",
            [2] = "Dusksage Stalker's Discipline",
            [3] = "Bosquestalker's Discipline",
            [4] = "Copsestalker's Discipline",
            [5] = "Wildstalker's Discipline",
            [6] = "Arbor Stalker's Discipline",
        },
        ["DefenseDisc"] = {
            [1] = "Weapon Shield Discipline",
        },
        ["Fireboon"] = {
            [1] = "Ashcloud Boon",
            [2] = "Wildfire Boon",
            [3] = "Skyfire Boon",
            [4] = "Pyroclastic Boon",
            [5] = "Lunarflare Boon",
        },
        ["Firenuke"] = {
            [1] = "Flame Lick",
            [2] = "Burst of Fire",
            [3] = "Ignite",
            [4] = "Flaming Arrow",
            [5] = "Burning Arrow",
            [6] = "Call of Flame",
            [7] = "FireStrike",
            [8] = "Brushfire",
            [9] = "Sylvan Burn",
            [10] = "Ancient: Burning Chaos",
            [11] = "Hearth Embers",
            [12] = "Scorched Earth",
            [13] = "Volcanic Ash",
            [14] = "Galvanic Ash",
            [15] = "Cataclysm Ash",
            [16] = "Burning Ash",
            [17] = "Beastwood Ash",
            [18] = "Vileoak Ash",
            [19] = "Wildfire Ash",
            [20] = "Skyfire Ash",
            [21] = "Pyroclastic Ash",
            [22] = "Lunarflare Ash",
        },
        ["Iceboon"] = {
            [1] = "Mistral Boon",
            [2] = "Windblast Boon",
            [3] = "Windgale Boon",
            [4] = "Windshear Boon",
            [5] = "Nocturnal Boon",
        },
        ["Icenuke"] = {
            [1] = "Bitter Wind",
            [2] = "Frozen Wind",
            [3] = "Frigid Wind",
            [4] = "Restless Wind",
            [5] = "Coagulated Wind",
        },
        ["Heartshot"] = {
            [1] = "Heartshot",
            [2] = "Heartsting",
            [3] = "Heartsting",
            [4] = "Heartslice",
            [5] = "Heartslash",
            [6] = "Heartsplit",
            [7] = "Heartcleave",
            [8] = "Heartsunder",
            [9] = "Heartruin",
        },
        ["EndRegenDisc"] = {
            [1] = "Second Wind",
            [2] = "Third Wind",
            [3] = "Fourth Wind",
            [4] = "Respite",
            [5] = "Reprieve",
            [6] = "Rest",
            [7] = "Breather",
            [8] = "Hiatus",
            [9] = "Relax",
            [10] = "Night's Calming",
            [11] = "Convalesce",
        },
        ["Coat"] = {
            [1] = "ThistleCoat",
            [2] = "Barbcoat",
            [3] = "Bramblecoat",
            [4] = "Spikecoat",
            [5] = "Thorncoat",
            [6] = "Bladecoat",
            [7] = "Briarcoat",
            [8] = "Spinecoat",
            [9] = "Quillcoat",
            [10] = "Burrcoat" ,
            [11] = "Spurcoat",
            [12] = "Nettlespear,",
            [13] = "Needlebarb,",
            [14] = "Rimespur,",
            [15] = "Moonthorn,",
            [16] = "Needlespike,",
        },
        ["Mask"] = {
            [1] = "Mask of the Stalker",
        },
        ["hunt"] = {
            [1] = "Engulfed by the Hunt",
            [2] = "Consumed by the Hunt",
            [3] = "Invigorated by the Hunt",
            [4] = "Galvanized by the Hunt",
            [5] = "Inspired by the Hunt",
            [6] = "Energized by the Hunt",
            [7] = "Spurred by the Hunt",
            [8] = "Provoked by the Hunt",
            [9] = "Steeled by the Hunt",
        },
        ["Heal"] = {
            [1] = "Elizerain Spring",
            [2] = "Darkflow Spring",
            [3] = "Meltwater Spring",
            [4] = "Wellspring",
            [5] = "Cloudfont",
            [6] = "Cloudburst",
            [7] = "Purespring",
            [8] = "Purefont",
            [9] = "Oceangreen Aquifer",
            [10] = "Dragonscale Aquifer",
            [11] = "Sunderock Springwater",
            [12] = "Sylvan Water",
            [13] = "Sylvan Light",
            [14] = "Chloroblast",
            [15] = "Greater Healing",
            [16] = "Light Healing",
            [17] = "Healing",
            [18] = "Minor Healing",
            [19] = "Salve",
        },
        ["Fastheal"] = {
            [1] = "Desperate Quenching",
            [2] = "Desperate Geyser",
            [3] = "Desperate Deluge",
            [4] = "Desperate Downpour",
            [5] = "Desperate Drenching",
            [6] = "Desperate Dousing",
            [7] = "Desperate Dewcloud",
            [8] = "Desperate Meltwater",
        },
        ["Totheal"] = {
            [1] = "Desperate Quenching",
            [2] = "Desperate Geyser",
            [3] = "Darkflow Spring",
            [4] = "Desperate Meltwater",
            [5] = "Meltwater Spring",
        },
        ["SnareSpells"] = {
            [1] = "Snare",
            [2] = "Tangling Weeds",
            [3] = "Ensnare",
            [4] = "Earthen Embrace",
            [5] = "Earthen Shackles",
        },
        ["FireFist"] = {
            [1] = "Firefist",
            [2] = "Nature's Precision",
            [3] = "Wolf Form",
            [4] = "Greater Wolf Form",
            [5] = "Feral Form",
        },
        ["DsBuff"] = {
            [1] = "Shield of Thistles",
            [2] = "Shield of Brambles",
            [3] = "Shield of Spikes",
            [4] = "Shield of Thorns",
            [5] = "Shield of Briar",
            [6] = "Shield of Needles",
            [7] = "Shield of Spurs",
            [8] = "Shield of DrySpines",
            [9] = "Shield of Nettlespikes",
            [10] = "Shield of Bramblespikes",
            [11] = "Shield of Nettlespines",
            [12] = "Shield of Nettlespears",
            [13] = "Shield of Needlebarbs",
            [14] = "Shield of Rimespurs",
            [15] = "Shield of Shadethorns",
        },
        ["SkinLike"] = {
            [1] = "Skin Like Wood",
            [2] = "Skin Like Rock",
            [3] = "Skin Like Steel",
            [4] = "Skin Like Diamond",
            [5] = "Skin Like Nature",
        },
        ["MoveSpells"] = {
            [1] = "Spirit of Falcons",
            [2] = "Spirit of Eagle",
            [3] = "Pack Shrew",
            [4] = "Spirit of the Shrew",
            [5] = "Spirit of Wolf",
        },
        ["Alliance"] = {
            [1] = "Bosquestalker's",
            [2] = "Wildstalker's Covenant",
            [3] = "Arbor Stalker's Coalition",
            [4] = "Dusksage Stalker's Conjunction",
        },
        ["AgiBuff"] = {
            [1] = "Feet Like Cat",
        },
        ["Cloak"] = {
            [1] = "Shalowain's Crucible,",
            [2] = "Luclin's Darkfire,",
            [3] = "Outrider's Ever-Burning,",
            [4] = "Lavastorm,",
            [5] = "Ro's Burning,",
        },
        ["Veil"] = {
            [1] = "Shadowveil",
            [2] = "Duskveil",
            [3] = "Frostveil",
            [4] = "Vaporous,",
            [5] = "Shimmering,",
            [6] = "Arbor,",
            [7] = "Veil of Alaris",
            [8] = "Nature,",
        },
        ["JoltingKicks"] = {
            [1] = "Jolting Frontkicks",
            [2] = "Jolting Hook Kicks",
            [3] = "Jolting Crescent Kicks",
            [4] = "Jolting Heel Kicks",
            [5] = "Jolting Cut Kicks",
            [6] = "Jolting Wheel Kicks",
            [7] = "Jolting Axe Kicks",
            [8] = "Jolting Roundhouse Kicks",
            [9] = "Jolting Drop Kicks",
        },
        ["AEBlades"] = {
            [1] = "Storm of Blades",
            [2] = "Squall Of Blades",
            [3] = "Gale of Blades",
            [4] = "Blizzard of Blades",
            [5] = "Tempest of Blades",
            [6] = "Maelstrom of Blades",
        },
        ["FocusedBlades"] = {
            [1] = "Focused Storm of Blades",
            [2] = "Focused Squall of Blades",
            [3] = "Focused Gale of Blades",
            [4] = "Focused Blizzard of Blades",
            [5] = "Focused Tempest of Blades",
        },
        ["ReflexSlashHeal"] = {
            [1] = "Reflexive Bladespurs",
            [2] = "Reflexive Nettlespears",
            [3] = "Reflexive Rimespurs",
        },
    },
    ['Rotations'] = {
    },
    ['DefaultConfig'] = {
    },
}



