local mq             = require('mq')
local RGMercUtils    = require("rgmercs.utils.rgmercs_utils")

return {
    ['Modes'] = {
        [1] = 'Tank',
        [2] = 'DPS',
        [3] = 'Healer',
        [4] = 'Hybrid',
    },
    ['ItemSets'] = {
        ['Epic'] = {
            [1] = "Staff of Phenomenal Power",
            [2] = "Staff of Prismatic Power",
        },
    },
    ['AbilitySets'] = {
        ['AllianceSpell'] = {
            [1] = "Malarian Mantle",
            [2] = "Frostbound Conjunction",
            [3] = "Frostbound Coalition",
            [4] = "Frostbound Covenant",
            [5] = "Frostbound Alliance",
        },
        ['DichoSpell'] = {
            [1] = "Ecliptic Fire",
            [2] = "Composite Fire",
            [3] = "Dissident Fire",
            [4] = "Dichotomic Fire",
        },
        ['IceClaw'] = {
            [1] = "Claw of the Void",
            [2] = "Claw of Gozzrem",
            [3] = "Claw of Travenro",
            [4] = "Claw of the Oceanlord",
            [5] = "Claw of the Icewing",
            [6] = "Claw of the Abyss",
            [7] = "Glacial Claw",
            [8] = "Claw of Selig",
            [9] = "Claw of Selay",
            [10] = "Claw of Vox",
            [11] = "Claw of Frost",
            [12] = "Claw of Ankexfen",
        },
        ['FireClaw'] = {
            [1] = "Claw of the Duskflame",
            [2] = "Claw of Sontalak",
            [3] = "Claw of Qunard",
            [4] = "Claw of the Flameweaver",
            [5] = "Claw of the Flamewing",
            [6] = "Claw of Ingot",
        },
        ['MagicClaw'] = {
            [1] = "Claw of Itzal",
            [2] = "Claw of Feshlak",
            [3] = "Claw of Ellarr",
            [4] = "Claw of the Indagatori",
            [5] = "Claw of the Ashwing",
            [6] = "Claw of the Battleforged",
        },
        ['CloudburstNuke'] = {
            [1] = "Cloudburst Lightningstrike",
            [2] = "Cloudburst Joltstrike",
            [3] = "Cloudburst Stormbolt",
            [4] = "Cloudburst Thunderbolt",
            [5] = "Cloudburst Stormstrike",
            [6] = "Cloudburst Thunderbolt",
            [7] = "Cloudburst Tempest",
            [8] = "Cloudburst Storm",
            [9] = "Cloudburst Levin",
            [10] = "Cloudburst Bolts",
            [11] = "Cloudburst Strike",
        },
        ['FuseNuke'] = {
            [1] = "Ethereal Twist"  ,
            [2] = "Ethereal Confluence",
            [3] = "Ethereal Braid",
            [4] = "Ethereal Fuse",
            [5] = "Ethereal Weave",
            [6] = "Ethereal Plait",
        },
        ['FireEtherealNuke'] = {
            [1] = "Ethereal Immolation",
            [2] = "Ethereal Ignition",
            [3] = "Ethereal Brand",
            [4] = "Ethereal Skyfire",
            [5] = "Ethereal Skyblaze",
            [6] = "Ethereal Incandescence",
            [7] = "Ethereal Blaze",
            [8] = "Ethereal Inferno",
            [9] = "Ethereal Combustion",
            [10] = "Ethereal Incineration",
            [11] = "Ethereal Conflagration",
            [12] = "Ether Flame",
        },
        ['IceEtherealNuke'] = {
                [1] = "Lunar Ice Comet",
                [2] = "Restless Ice Comet",
                [3] = "Ethereal Icefloe",
                [4] = "Ethereal Rimeblast",
                [5] = "Ethereal Hoarfrost",
                [6] = "Ethereal Frost",
                [7] = "Ethereal Glaciation",
                [8] = "Ethereal Iceblight",
                [9] = "Ethereal Rime",
                [10] = "Ethereal Freeze",
        },
        ['MagicEtherealNuke'] = {
                [1] = "Ethereal Mortar",
                [2] = "Ethereal Blast",
                [3] = "Ethereal Volley",
                [4] = "Ethereal Flash",
                [5] = "Ethereal Salvo",
                [6] = "Ethereal Barrage",
                [7] = "Ethereal Blitz",
        },
        ['ChaosNuke'] = {
            [1] = "Chaos Flame",
            [2] = "Chaos Inferno",
            [3] = "Chaos Burn", 
            [4] = "Chaos Scintillation",
            [5] = "Chaos Incandescence",
            [6] = "Chaos Blaze",
            [7] = "Chaos Char",    
            [8] = "Chaos Conflagration",
            [9] = "Chaos Immolation",
            [10] = "Chaos Flame",
        },
        ['VortexNuke'] = {
            -- NOTE: ${Spell[${VortexNuke}].ResistType} can be used to determine which resist type is getting debuffed
            [1] = "Shadebright Vortex",
            [2] = "Thaumaturgic Vortex",
            [3] = "Stormjolt Vortex",
            [4] = "Shocking Vortex",
            -- Hoarfrost Vortex has a Fire Debuff
            [5] = "Hoarfrost Vortex",
            -- Ether Vortex has a Cold Debuff
            [6] = "Ether Vortex",
            -- Incandescent Vortex has a Magic Debuff
            [7] = "Incandescent Vortex",
            -- Frost Vortex has a Fire Debuff
            [8] = "Frost Vortex",
            -- Power Vortex has a Cold Debuff
            [9] = "Power Vortex",
            -- Flame Vortex has a Magic Debuff
            [10] = "Flame Vortex",
            -- Ice Vortex has a Fire Debuff
            [11] = "Ice Vortex",
            -- Mana Vortex has a Cold Debuff
            [12] = "Mana Vortex",
            -- Fire Vortex has a Magic Debuff
            [13] = "Fire Vortex",
        },
        ['WildNuke'] = {
            [1] = "Wildspell Strike",
            [2] = "Wildflame Strike",
            [3] = "Wildscorch Strike",
            [4] = "Wildflash Strike", 
            [5] = "Wildflash Barrage",
            [6] = "Wildether Barrage",
            [7] = "Wildspark Barrage",
            [8] = "Wildmana Barrage",    
            [9] = "Wildmagic Blast",
            [10] = "Wildmagic Burst",
            [11] = "Wildmagic Strike",
        },
        ['FireNuke'] = {
            [1] = "Kindleheart's Fire",
            [2] = "The Diabo's Fire",
            [3] = "Dagarn's Fire",
            [4] = "Dragoflux's Fire",
            [5] = "Narendi's Fire",
            [6] = "Gosik's Fire",
            [78] = "Daevan's Fire",
            [8] = "Lithara's Fire",
            [9] = "Klixcxyk's Fire",
            [10] = "Inizen's Fire",  
            [11] = "Sothgar's Flame",
            [12] = "Corona Flare",
            [13] = "White Fire",
            [14] = "Garrison's Superior Sundering",
            [15] = "Conflagration",
            [16] = "Inferno Shock",   
            [17] = "Flame Shock",
            [18] = "Fire Bolt",
            [19] = "Shock of Fire",  
        },
        ['IceNuke'] = {
            [1] = "Glacial Ice Cascade",
            [2] = "Tundra Ice Cascade",
            [3] = "Restless Ice Cascade",
            [4] = "Icefloe Cascade",
            [5] = "Rimeblast Cascade",
            [6] = "Hoarfrost Cascade",
            [7] = "Rime Cascade",
            [8] = "Glacial Cascade",
            [9] = "Icesheet Cascade",
            [10] = "Glacial Collapse",   
            [11] = "Icefall Avalanche",
            [12] = "Gelidin Comet", 
            [13] = "Ice Meteor",
            [14] = "Ice Spear of Solist",
            [15] = "Frozen Harpoon",
            [16] = "Ice Comet",    
            [17] = "Ice Shock",
            [18] = "Frost Shock",
            [19] = "Shock of Ice",   
            [20] = "Frost Bolt",  
            [21] = "Blast of Cold",
        },
        ['MagicNuke'] = {
            [1] = "Lightning Cyclone",
            [2] = "Lightning Maelstrom" ,
            [3] = "Lightning Roar",
            [4] = "Lightning Tempest",
            [5] = "Lightning Storm",
            [6] = "Lightning Squall",
            [7] = "Lightning Swarm",
            [8] = "Lightning Helix",
            [9] = "Ribbon Lightning",
            [10] = "Rolling Lightning",
            [11] = "Ball Lightning",
            [12] = "Spark of Lightning",  
            [13] = "Draught of Lightning",
            [14] = "Elnerick's Electrical Rending",
            [15] = "Draught of Jiva",
            [16] = "Voltaic Draught",
            [17] = "Rend",
            [18] = "Lightning Shock",   
            [19] = "Thunder Strike",
            [20] = "Garrison's Mighty Mana Shock",
            [21] = "Lightning Bolt",  
            [22] = "Shock of Lightning", 
        },
        ['StunSpell'] = {
            [1] = "Teladaka",
            [2] = "Teladaja",
            [3] = "Telajaga",
            [4] = "Telanata",
            [5] = "Telanara",   
            [6] = "Telanaga",
            [7] = "Telanama",
            [8] = "Telakama",   
            [9] = "Telajara",
            [10] = "Telajasz", 
            [11] = "Telakisz",
            [12] = "Telekara",
            [13] = "Telaka",
            [14] = "Telekin",    
            [15] = "Markar's Discord",
            [16] = "Markar's Clash",
            [17] = "Tishan's Clash",
        },
        ['SelfHPBuff'] = {
            [1] = "Shield of Memories",
            [2] = "Shield of Shadow",
            [3] = "Shield of Restless Ice",
            [4] = "Shield of Scales",
            [5] = "Shield of the Pellarus",
            [6] = "Shield of the Dauntless",
            [7] = "Shield of Bronze",
            [8] = "Shield of Dreams",
            [9] = "Shield of the Void",
            [10] = "Bulwark of the Crystalwing",
            [11] = "Shield of the Crystalwing",
            [12] = "Ether Shield",   
            [13] = "Shield of Maelin",
            [14] = "Shield of the Arcane", 
            [15] = "Shield of the Magi",
            [16] = "Arch Shielding",
            [17] = "Greater Shielding",
            [18] = "Major Shielding",    
            [19] = "Shielding",
            [20] = "Lesser Shielding",
            [21] = "Minor Shielding",
        },
        ['FamiliarBuff'] = {
            [1] = "Greater Familiar",
            [2] = "Familiar",
            [3] = "Lesser Familiar",   
            [4] = "Minor Familiar",  
        },
        ['SelfRune1'] = {
            [1] = "Aegis of Remembrance",
            [2] = "Aegis of the Umbra",
            [3] = "Aegis of the Crystalwing",
            [4] = "Armor of Wirn",   
            [5] = "Armor of the Codex",
            [6] = "Armor of the Stonescale", 
            [7] = "Armor of the Crystalwing",
            [8] = "Dermis of the Crystalwing",
            [9] = "Squamae of the Crystalwing",
            [10] = "Laminae of the Crystalwing",    
            [11] = "Scales of the Crystalwing",
            [12] = "Ether Skin",
            [13] = "Force Shield",
        },
        ['StripBuffSpell'] = {
            [1] = "Annul Magic",   
            [2] = "Nullify Magic",
            [3] = "Cancel Magic",
        },
        ['TwincastSpell'] = {
            [1] = "Twincast",
        },
        ['GambitSpell'] = {
            [1] = "Anodyne Gambit",
            [2] = "Idyllic Gambit",
            [3] = "Musing Gambit",
            [4] = "Quiescent Gambit",   
            [5] = "Bucolic Gambit",
        },
        ['PetSpell'] = {
            [1] = "Kindleheart's Pyroblade",
            [2] = "Diabo Xi Fer's Pyroblade",
            [3] = "Ricartine's Pyroblade",
            [4] = "Virnax's Pyroblade",   
            [5] = "Yulin's Pyroblade",
            [6] = "Mul's Pyroblade", 
            [7] = "Burnmaster's Pyroblade",
            [8] = "Lithara's Pyroblade",
            [9] = "Daveron's Pyroblade",
            [10] = "Euthanos' Flameblade",    
            [11] = "Ethantis's Burning Blade",
            [12] = "Solist's Frozen Sword",
            [13] = "Flaming Sword of Xuzl",
        },
        ['RootSpell'] = {
            [1] = "Greater Fetter",
            [2] = "Fetter",
            [3] = "Paralyzing Earth",    
            [4] = "Immobilize",
            [5] = "Instill",
            [6] = "Root",
        },
        ['SnareSpell'] = {
            [1] = "Atol's Concussive Shackles", 
            [2] = "Atol's Spectral Shackles",
            [3] = "Bonds of Force",
        },
        ['EvacSpell'] = {
            [1] = "Evacuate",
            [2] = "Lesser Evacuate",
        },
        ['HarvestSpell'] = {
            [1] = "Contemplative Harvest",
            [2] = "Shadow Harvest",
            [3] = "Quiet Harvest",   
            [4] = "Musing Harvest",
            [5] = "Quiescent Harvest", 
            [6] = "Bucolic Harvest",
            [7] = "Placid Harvest",
            [8] = "Soothing Harvest",
            [9] = "Serene Harvest",    
            [10] = "Tranquil Harvest",
            [11] = "Patient Harvest",
            [12] = "Harvest",
        },
        ['JoltSpell'] = {
            [1] = "Spinalfreeze",
            [2] = "Cerebrumfreeze",
            [3] = "Neurofreeze",
            [4] = "Cortexfreeze",   
            [5] = "Synapsefreeze",
            [6] = "Flashfreeze", 
            [7] = "Skullfreeze",
            [8] = "Thoughtfreeze",
            [9] = "Brainfreeze",
            [10] = "Mindfreeze",    
            [11] = "Concussive Flash",
            [12] = "Concussive Burst",
            [13] = "Concussive Blast", 
            [14] = "Ancient: Greater Concussion",
            [15] = "Concussion",
        },
        -- Lure Spells
        ['IceLureNuke'] = {
            [1] = "Lure of Frost",
            [2] = "Lure of Ice",
            [3] = "Icebane",
            [4] = "Rimelure",
            [5] = "Voidfrost Lure",
            [6] = "Glacial Lure",
            [7] = "Frigid Lure",
            [8] = "Lure of Isaz",
            [9] = "Lure of the Wastes",
            [10] = "Lure of the Depths",
            [11] = "Lure of Travenro",
            [12] = "Lure of Restless Ice",
            [13] = "Lure of the Cold Moon",
            [14] = "Lure of Winter Memories",
        },
        ['FireLureNuke'] = {
            [1] = "Enticement of Flame",
            [2] = "Lure of Flame", 
            [3] = "Lure of Ro",
            [4] = "Firebane",
            [5] = "Lavalure", 
            [6] = "Pyrolure",
            [7] = "Flarelure",
            [8] = "Flamelure", 
            [9] = "Blazelure",
            [10] = "MagmaLure",
            [11] = "PlasmaLure", 
            [12] = "Lure of Qunard",
            [13] = "Lure of Sontalak",
            [14] = "Lure of Fyrthek",
            [15] = "Lure of the Arcanaforged",
        },
        ['MagicLureNuke'] = {
            [1] = "Lure of Lightning",
            [2] = "Lure of Thunder",
            [3] = "Lightningbane",
            [4] = "Permeating Ether",
        },
        -- Fast Nukes 
        ['FastIceNuke'] = {
            [1] = "Draught of Ice",
            [2] = "Frost Shock",
            [3] = "Shock of Ice",
            [4] = "Draught of E`ci",
            [5] = "Black Ice",
            [7] = "Spark of Ice",   
        },
        ['FastFireNuke'] = {
            [1] = "Shock of Fire",
            [2] = "Flame Shock",
            [3] = "Inferno Shock",
            [4] = "Draught of Fire",
            [5] = "Draught of Ro",
            [6] = "Chaos Flame",
            [7] = "Spark of Fire",
        },
        ['FastMagicNuke'] = {
            [1] = "Voltaic Draught",
            [2] = "Draught of Lightning",
            [3] = "Spark of Lightning",  
            [4] = "Leap of Stormjolts",  
            [5] = "Leap of Stormbolts",
            [6] = "Leap of Static Sparks",
            [7] = "Leap of Plasma",
            [8] = "Leap of Corposantum",
            [9] = "Leap of Static Jolts",
            [10] = "Leap of Static Bolts",
            [11] = "Leap of Sparks",
            [12] = "Leap of Levinsparks",
        },
        -- Rain Spells Listed here are used Primarily for TLP Mode.
        -- Magic Rain - Only have 3 of them so Not Sustainable.
        ['IceRainNuke'] = {
            [1] = "Icestrike",
            [2] = "Frost Storm",
            [3] = "Tears of Prexus",
            [4] = "Tears of Marr",
            [5] = "Gelid Rains",
            [6] = "Icicle Deluge",
            [7] = "Icicle Storm",
            [8] = "Icicle Torrent",
            [9] = "Hail Torrent",
            [10] = "Frost Torrent",
            [11] = "Tamagrist Torrent",
            [12] = "Darkwater Torrent",
            [13] = "Frostbite Torrent",
            [14] = "Coldburst Torrent",
            [15] = "Hypothermic Torrent",
            [16] = "Rimeclaw Torrent",
        },
        ['FireRainNuke'] = {
            [1] = "Firestorm",
            [2] = "Lava Storm",
            [3] = "Tears of Solusek",
            [4] = "Tears of Ro",
            [5] = "Tears of the Sun",
            [6] = "Tears of the Betrayed",
            [7] = "Tears of the Forsaken",
            [8] = "Tears of the Pyrilen",
            [9] = "Tears of Flame",
            [10] = "Tears of Daevan",
            [11] = "Tears of Gosik",
            [12] = "Tears of Narendi",
            [13] = "Tears of Dragoflux",
            [14] = "Tears of Wildfire",
            [15] = "Tears of Night Fire",
            [16] = "Tears of the Rescued",
        },
        ['FireRainLureNuke'] = {
            [1] = "Volcanic Burst",
            [2] = "Tears of Arlyxir",
            [3] = "Meteor Storm",
            [4] = "Volcanic Eruption",
            [5] = "Pyroclastic Eruption",
            [6] = "Magmatic Eruption",
            [7] = "Magmatic Downpour",
            [8] = "Magmatic Outburst",
            [9] = "Magmatic Vent",
            [10] = "Magmatic Burst",
            [11] = "Magmatic Explosion",
            [12] = "Volcanic Downpour",
            [13] = "Volcanic Barrage",
        },
        -- Large 8 Second Cast Nukes
        ['BigIceNuke'] = {
            -- Big Ice Nukes  50-69 
            [1] = "Ice Comet",
            [2] = "Ice Spear of Solist",
            [3] = "Ancient: Destruction of Ice",
            [4] = "Ice Meteor",
            [5] = "Gelidin Comet",
        },
        ['BigFireNuke'] = {
            -- Big Fire Nukes
            [1] = "Conflagration",
            [2] = "Sunstrike",
            [3] = "Garrison's Superior Sundering",
            [4] = "Strike of Solusek",
            [5] = "White Fire",
            [6] = "Ether Flame",    
            [7] = "Corona Flare",
        },
        ['BigMagicNuke'] = {
            -- Big Magic Nukes
            [1] = "Rend",
            [2] = "Elnerick's Electrical Rending",
            [3] = "Agnarr's Thunder",
            [4] = "Shock of Magic",
            [5] = "Thundaka",
            [6] = "Mana Weave",
        },
    },

    ['ChatBegList'] = {
        ['WizBegs'] = {
            ['bindme'] = {
                ['spell'] = "Bind Affinity",
                ['sender'] = true,
            },
            ['gatenorth'] = {
                ['spell'] = "North Gate",
                ['sender'] = true,
            },
            ['gatefay'] = {
                ['spell'] = "Fay Gate",
                ['sender'] = true,
            },      
            ['portalnorth'] = {
                ['spell'] = "North Portal",
                ['sender'] = true,
            },
            ['portalfay'] = { 
                ['spell'] = "Fay Portal",
                ['sender'] = true,
            },
            ['portallcea'] = {
                ['spell'] = { "Lceanium Portal",
                ['sender'] = true,
            },
            },
        },
    },
    ['Rotations'] = {
        ['Tank'] = {
            ['Rotation'] = {
                ['Burn'] = {
                    [1] = {},
                },
                ['Debuff'] = {
                    [1] = {},
                },
                ['Heal'] = {
                    [1] = {},
                },
                ['DPS'] = {
                    [1] = {},
                },
                ['Downtime'] = {
                    [1] = {},
                },
            },
            ['Spells'] = {
                [1] = { name="", gem=1 },
                [2] = { name="", gem=2 },
                [3] = { name="", gem=3},
                [4] = { name="", gem=4},
                [5] = { name="", gem=5 },
                [6] = { name="", gem=6 },
                [7] = { name="", gem=7 },
                [8] = { name="", gem=8 },
                [9] = { name="", gem=9 },
                [10] = { name="", gem=10 },
                [11] = { name="", gem=11 },
                [12] = { name="", gem=12 },
            },
        },
        ['DPS'] = {
            ['Rotation'] = {
                ['Burn'] = {
                    [1] = {},
                },
                ['Debuff'] = {
                    [1] = {},
                },
                ['Heal'] = {
                    [1] = {},
                },
                ['DPS'] = {
                    [1] = {},
                },
                ['Downtime'] = {
                    [1] = {},
                },
            },
            ['Spells'] = {
                [1] = { name="", gem=1 },
                [2] = { name="", gem=2 },
                [3] = { name="", gem=3},
                [4] = { name="", gem=4},
                [5] = { name="", gem=5 },
                [6] = { name="", gem=6 },
                [7] = { name="", gem=7 },
                [8] = { name="", gem=8 },
                [9] = { name="", gem=9 },
                [10] = { name="", gem=10 },
                [11] = { name="", gem=11 },
                [12] = { name="", gem=12 },
            },
        },
        ['Healer'] = {
            ['Rotation'] = {
                ['Burn'] = {
                    [1] = {},
                },
                ['Debuff'] = {
                    [1] = {},
                },
                ['Heal'] = {
                    [1] = {},
                },
                ['DPS'] = {
                    [1] = {},
                },
                ['Downtime'] = {
                    [1] = {},
                },
            },
            ['Spells'] = {
                [1] = { name="", gem=1 },
                [2] = { name="", gem=2 },
                [3] = { name="", gem=3},
                [4] = { name="", gem=4},
                [5] = { name="", gem=5 },
                [6] = { name="", gem=6 },
                [7] = { name="", gem=7 },
                [8] = { name="", gem=8 },
                [9] = { name="", gem=9 },
                [10] = { name="", gem=10 },
                [11] = { name="", gem=11 },
                [12] = { name="", gem=12 },
            },
        },
        ['Hybrid'] = {
            ['Rotation'] = {
                ['Burn'] = {
                    [1] = {},
                },
                ['Debuff'] = {
                    [1] = {},
                },
                ['Heal'] = {
                    [1] = {},
                },
                ['DPS'] = {
                    [1] = {},
                },
                ['Downtime'] = {
                    [1] = {},
                },
            },
            ['Spells'] = {
                [1] = { name="", gem=1 },
                [2] = { name="", gem=2 },
                [3] = { name="", gem=3},
                [4] = { name="", gem=4},
                [5] = { name="", gem=5 },
                [6] = { name="", gem=6 },
                [7] = { name="", gem=7 },
                [8] = { name="", gem=8 },
                [9] = { name="", gem=9 },
                [10] = { name="", gem=10 },
                [11] = { name="", gem=11 },
                [12] = { name="", gem=12 },
            },
        },
        ['DefaultConfig'] = {
            ['Mode'] = '1',
        },
    },
}